/** @type {import('jest').Config} */
module.exports = {
  testEnvironment: 'jsdom',
  roots: ['<rootDir>/src/__tests__'],
  transform: {
    '^.+\\.jsx?$': ['ts-jest', {
      diagnostics: false,
      tsconfig: {
        allowJs: true,
        module: 'commonjs',
        moduleResolution: 'node',
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        skipLibCheck: true,
      },
    }],
    '^.+\\.(ts|tsx)$': ['ts-jest', {
      tsconfig: {
        jsx: 'react-jsx',
        module: 'commonjs',
        moduleResolution: 'node',
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        strict: false,
        skipLibCheck: true,
        baseUrl: '.',
        paths: {
          '@/*': ['src/*'],
          '@components/*': ['src/components/*'],
          '@features/*': ['src/features/*'],
          '@services/*': ['src/services/*'],
          '@utils/*': ['src/utils/*'],
          '@hooks/*': ['src/hooks/*'],
          '@contexts/*': ['src/contexts/*'],
          '@config/*': ['src/config/*'],
          '@types/*': ['src/types/*'],
          '@assets/*': ['src/assets/*'],
          '@app/*': ['src/app/*'],
          '@pages/*': ['src/pages/*'],
        },
      },
    }],
  },
  moduleNameMapper: {
    '^@design-system/(.*)$': '<rootDir>/design-system/$1',
    '^@features/(.*)$': '<rootDir>/src/features/$1',
    '^react$': '<rootDir>/node_modules/react/index.js',
    '^react-dom$': '<rootDir>/node_modules/react-dom/index.js',
    '^react-dom/(.*)$': '<rootDir>/node_modules/react-dom/$1',
    '^react/(.*)$': '<rootDir>/node_modules/react/$1',
    '\\.(css|less|scss|sass)$': '<rootDir>/src/__tests__/__mocks__/styleMock.js',
    '^react-force-graph-2d$': '<rootDir>/src/__tests__/__mocks__/react-force-graph-2d.js',
    '^react-markdown$': '<rootDir>/src/__tests__/__mocks__/react-markdown.js',
    '^react-syntax-highlighter/dist/esm/styles/(.*)$': '<rootDir>/src/__tests__/__mocks__/react-syntax-highlighter-styles.js',
    '^react-syntax-highlighter$': '<rootDir>/src/__tests__/__mocks__/react-syntax-highlighter.js',
    '^remark-gfm$': '<rootDir>/src/__tests__/__mocks__/remark-gfm.js',
    '^remark-math$': '<rootDir>/src/__tests__/__mocks__/remark-math.js',
    '^rehype-katex$': '<rootDir>/src/__tests__/__mocks__/rehype-katex.js',
    '^rehype-raw$': '<rootDir>/src/__tests__/__mocks__/rehype-raw.js',
    '^@almadar/(.*)$': '<rootDir>/src/__tests__/__mocks__/almadarMock.js',
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
  setupFiles: ['<rootDir>/src/__tests__/setupGlobals.ts'],
  transformIgnorePatterns: [
    '/node_modules/(?!(@almadar|@reduxjs)/)',
  ],
  testPathIgnorePatterns: ['/node_modules/'],
};
