import type { Meta, StoryObj } from "@storybook/react";
import { SubjectOverviewBoard } from "./SubjectOverviewBoard";
import type { KnowledgeNode, KnowledgeSubject } from "../types/knowledge";

const meta: Meta<typeof SubjectOverviewBoard> = {
  title: "KFlow/Organisms/SubjectOverviewBoard",
  component: SubjectOverviewBoard,
  parameters: { layout: "padded" },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof SubjectOverviewBoard>;

// Realistic JavaScript knowledge data (subset of converted data)
const jsSubject: KnowledgeSubject = {
  id: "formal-cs-javascript",
  name: "JavaScript",
  domain: "formal",
  discipline: "Computer Science",
  nodeCount: 371,
  maxDepth: 9,
  fileSize: 241022,
  rootNodeId: "javascript-javascript",
};

const rootNode: KnowledgeNode = {
  id: "javascript-javascript",
  title: "JavaScript",
  description: "A high-level, interpreted programming language that conforms to the ECMAScript specification.",
  domain: "formal",
  discipline: "Computer Science",
  subject: "JavaScript",
  depth: 0,
  parentId: "",
  childIds: ["javascript-lexical-scoping", "javascript-data-structures", "javascript-es6", "javascript-dom", "javascript-async"],
  resourceUrls: [],
  notes: "",
  nodeType: "root",
};

const sampleNodes: KnowledgeNode[] = [
  rootNode,
  {
    id: "javascript-lexical-scoping",
    title: "Lexical Scoping",
    description: "Lexical scoping means that the accessibility of variables is determined by the position of the variables within nested scopes.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 1,
    parentId: "javascript-javascript",
    childIds: ["javascript-closures", "javascript-hoisting"],
    resourceUrls: ["https://stackoverflow.com/questions/1047454/what-is-lexical-scope"],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-closures",
    title: "Closures",
    description: "A closure is the combination of a function bundled with references to its surrounding state (the lexical environment).",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 2,
    parentId: "javascript-lexical-scoping",
    childIds: [],
    resourceUrls: ["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures"],
    notes: "Great example of lexical vs dynamic scoping",
    nodeType: "concept",
  },
  {
    id: "javascript-hoisting",
    title: "Hoisting",
    description: "Variable and function declarations are moved to the top of their scope before code execution.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 2,
    parentId: "javascript-lexical-scoping",
    childIds: [],
    resourceUrls: [],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-data-structures",
    title: "Data Structures",
    description: "Core data structures in JavaScript including arrays, objects, maps, and sets.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 1,
    parentId: "javascript-javascript",
    childIds: ["javascript-arrays", "javascript-maps"],
    resourceUrls: ["https://github.com/thejameskyle/itsy-bitsy-data-structures"],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-arrays",
    title: "Arrays",
    description: "Ordered collections of values with integer-based indexing.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 2,
    parentId: "javascript-data-structures",
    childIds: ["javascript-array-methods"],
    resourceUrls: [],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-array-methods",
    title: "Array Methods",
    description: "Built-in methods like map, filter, reduce, forEach, find, and more.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 3,
    parentId: "javascript-arrays",
    childIds: [],
    resourceUrls: [],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-maps",
    title: "Maps & Sets",
    description: "Key-value collections (Map) and unique value collections (Set) introduced in ES6.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 2,
    parentId: "javascript-data-structures",
    childIds: [],
    resourceUrls: [],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-es6",
    title: "ES6+ Features",
    description: "Modern JavaScript features introduced in ECMAScript 2015 and later.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 1,
    parentId: "javascript-javascript",
    childIds: ["javascript-arrow-functions", "javascript-destructuring"],
    resourceUrls: [],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-arrow-functions",
    title: "Arrow Functions",
    description: "Concise syntax for writing function expressions with lexical this binding.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 2,
    parentId: "javascript-es6",
    childIds: [],
    resourceUrls: [],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-destructuring",
    title: "Destructuring",
    description: "Extract values from arrays or properties from objects into distinct variables.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 2,
    parentId: "javascript-es6",
    childIds: [],
    resourceUrls: [],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-dom",
    title: "DOM Manipulation",
    description: "Interacting with the Document Object Model to create dynamic web pages.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 1,
    parentId: "javascript-javascript",
    childIds: [],
    resourceUrls: ["https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model"],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-async",
    title: "Asynchronous JavaScript",
    description: "Callbacks, promises, and async/await for handling asynchronous operations.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 1,
    parentId: "javascript-javascript",
    childIds: ["javascript-promises"],
    resourceUrls: [],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-promises",
    title: "Promises",
    description: "An object representing the eventual completion or failure of an asynchronous operation.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 2,
    parentId: "javascript-async",
    childIds: [],
    resourceUrls: [],
    notes: "",
    nodeType: "concept",
  },
  {
    id: "javascript-mdn-resource",
    title: "MDN Web Docs",
    description: "Comprehensive documentation for web technologies.",
    domain: "formal",
    discipline: "Computer Science",
    subject: "JavaScript",
    depth: 1,
    parentId: "javascript-javascript",
    childIds: [],
    resourceUrls: ["https://developer.mozilla.org/en-US/docs/Web/JavaScript"],
    notes: "",
    nodeType: "resource",
  },
];

export const Default: Story = {
  args: {
    entity: {
      subject: jsSubject,
      nodes: sampleNodes,
      rootNode,
    },
    selectNodeEvent: "SELECT_NODE",
    navigateBreadcrumbEvent: "NAVIGATE_BREADCRUMB",
  },
};

export const PhysicsSubject: Story = {
  args: {
    entity: {
      subject: {
        id: "natural-physics",
        name: "Physics",
        domain: "natural",
        discipline: "Physics",
        nodeCount: 245,
        maxDepth: 7,
        fileSize: 190787,
        rootNodeId: "physics-root",
      },
      nodes: [
        {
          id: "physics-root",
          title: "Physics",
          description: "The natural science of matter, its motion and behavior through space and time.",
          domain: "natural",
          discipline: "Physics",
          subject: "Physics",
          depth: 0,
          parentId: "",
          childIds: ["physics-mechanics", "physics-thermodynamics"],
          resourceUrls: [],
          notes: "",
          nodeType: "root",
        },
        {
          id: "physics-mechanics",
          title: "Classical Mechanics",
          description: "Study of the motion of bodies under the action of forces.",
          domain: "natural",
          discipline: "Physics",
          subject: "Physics",
          depth: 1,
          parentId: "physics-root",
          childIds: [],
          resourceUrls: ["https://en.wikipedia.org/wiki/Classical_mechanics"],
          notes: "",
          nodeType: "concept",
        },
        {
          id: "physics-thermodynamics",
          title: "Thermodynamics",
          description: "Study of heat, work, temperature, and their relation to energy and entropy.",
          domain: "natural",
          discipline: "Physics",
          subject: "Physics",
          depth: 1,
          parentId: "physics-root",
          childIds: [],
          resourceUrls: [],
          notes: "",
          nodeType: "concept",
        },
      ],
      rootNode: {
        id: "physics-root",
        title: "Physics",
        description: "The natural science of matter, its motion and behavior through space and time.",
        domain: "natural",
        discipline: "Physics",
        subject: "Physics",
        depth: 0,
        parentId: "",
        childIds: ["physics-mechanics", "physics-thermodynamics"],
        resourceUrls: [],
        notes: "",
        nodeType: "root",
      },
    },
    selectNodeEvent: "SELECT_NODE",
  },
};
