/**
 * @deprecated These types are deprecated. Use features/knowledge-graph/types instead.
 * This file contains the old concept types and will be removed in a future version.
 * 
 * Migration guide:
 * - Use NodeBasedKnowledgeGraph instead of ConceptGraph
 * - Use GraphNode instead of Concept (for graph structure)
 * - Use ConceptDisplay from graphQueryService for UI display
 */

// Concept types matching server types

// Bloom's Taxonomy cognitive levels
export type BloomLevel = 'remember' | 'understand' | 'apply' | 'analyze' | 'evaluate' | 'create';

// User progress tracking for learning science features
export interface UserProgress {
  activationResponse?: string; // User's response to pre-lesson activation question
  reflectionNotes?: string[]; // User's notes for inline reflection prompts
  bloomAnswered?: Record<number, boolean>; // Which Bloom questions have been answered (by index)
  bloomLevelsCompleted?: BloomLevel[]; // Which Bloom levels user has practiced
  lastStudied?: Date; // When user last engaged with this concept
  masteryLevel?: 0 | 1 | 2 | 3; // 0=not started, 1=learning, 2=practiced, 3=mastered
}

export interface Concept {
  id: string;               // ID generated on server side
  name: string;             // Concept name (equivalent to title in notes)
  description: string;       // Concept description (equivalent to content in notes)
  goal?: string;            // Goal for level concepts (top-level concepts that represent layers)
  parents: string[];         // Array of parent concept names
  children: string[];       // Array of child concept names
  layer?: number;           // Optional layer number for progressive expansion (deprecated - will be removed after migration)
  subLayer?: string;        // Optional sub-layer identifier
  isSeed?: boolean;         // Whether this is the seed concept
  isExpanded?: boolean;     // Whether the concept is expanded in the mindmap view
  lesson?: string;          // Optional markdown lesson generated by explain operation
  sequence?: number;        // Sequence order to preserve insertion ordering
  focus?: string;           // Learning focus extracted from seed concept description
  difficulty?: ConceptDifficulty; // Difficulty level (beginner, intermediate, advanced)
  prerequisites?: string[]; // Array of prerequisite concept names
  isAutoGenerated?: boolean; // Flag for concepts auto-created from prerequisites
  isPrerequisite?: boolean; // Flag indicating if this concept is a prerequisite for another concept
  flash?: FlashCard[]; // Array of flash cards for the concept
  userProgress?: UserProgress; // User's learning progress on this concept
  questions?: QuestionAnswer[]; // Array of questions and answers asked about this concept
  notes?: NoteItem[]; // Array of user notes for the lesson
}

/**
 * Note item structure
 */
export interface NoteItem {
  id: string; // Unique ID for the note (also used as highlightId)
  text: string; // The note content
  selectedText?: string; // Full selected text for display
  selectedTextChunks?: string[]; // Chunks of selected text for highlighting
  timestamp?: number; // Timestamp when the note was created
}

/**
 * Question and answer structure
 */
export interface QuestionAnswer {
  question: string; // The question asked
  answer: string; // The answer received
  selectedText?: string; // Full selected text for display
  selectedTextChunks?: string[]; // Chunks of selected text for highlighting
  highlightId?: string; // Shared ID for all chunks (if not using question/answer ID)
  timestamp?: number; // Timestamp when the question was asked
}


/**
 * Flash card structure
 */
export interface FlashCard {
  front: string; // Question or prompt (front of the card)
  back: string; // Answer or explanation (back of the card)
}

// Practice item type
export interface PracticeItem {
  type: 'question' | 'project';
  question: string;
  answer: string;
}

// Layer data structure matching server LayerDocument
export interface LayerData {
  layerNumber: number;
  prompt: string;
  response: string;
  goal?: string;
  conceptIds: string[];
  practiceExercises?: PracticeItem[]; // Practice exercises for this layer
  createdAt?: number;
}

// ConceptGraph represents a complete concept graph with a seed concept
export interface ConceptGraph {
  id: string;               // Unique ID for the graph
  seedConceptId: string;    // ID of the seed concept
  concepts: Map<string, Concept>;  // All concepts in the graph keyed by concept name (matching server type)
  layers?: Map<number, LayerData>; // Map of layer number to layer data
  createdAt: number;        // Timestamp when the graph was created
  updatedAt: number;        // Timestamp when the graph was last updated
  model?: string;           // LLM model used to generate concepts (e.g., "gpt-5-nano", "gemini-2.5-flash")
  goalFocused?: boolean;    // Whether subsequent layers should be goal-focused (project-based) (default: false)
  difficulty?: ConceptDifficulty; // Difficulty level (beginner, intermediate, advanced)
  focus?: string;           // Learning focus for the graph
  name?: string;            // Graph name (same as seed concept name)
}

// JSON-serializable version of ConceptGraph for localStorage
export interface ConceptGraphJSON {
  id: string;
  seedConceptId: string;
  concepts: Record<string, Concept>;  // Map serialized as Record for JSON
  layers?: Record<number, LayerData>; // Map serialized as Record for JSON
  createdAt: number;
  updatedAt: number;
  model?: string;           // LLM model used to generate concepts
  goalFocused?: boolean;    // Whether subsequent layers should be goal-focused (project-based) (default: false)
  difficulty?: ConceptDifficulty; // Difficulty level (beginner, intermediate, advanced)
  focus?: string;           // Learning focus for the graph
  name?: string;            // Graph name (same as seed concept name)
}

// Extended concept with metadata (for future use)
export interface ExtendedConcept extends Concept {
  attention_score?: number;
  validation_score?: number;
  importance?: 'low' | 'medium' | 'high';
}

export type ConceptDifficulty = 'beginner' | 'intermediate' | 'advanced';

