import React, { useEffect, useMemo, useState } from 'react';
import { Concept, ConceptGraph } from '../types';
import ConceptName from './ConceptName';
import { ConceptDescription } from '../../../components/molecules/ConceptDescription';
import ConceptParents from './ConceptParents';
import { Layers, Loader2, Minus, Plus, ChevronDown, ChevronRight, Target, Info, BookOpen } from 'lucide-react';
import { useConceptLevels } from '../hooks/useConceptLevels';
import LayerPracticeModal from './LayerPracticeModal';
import { PrerequisiteList } from '../../../components/organisms/PrerequisiteList';

interface ConceptListItemProps {
  concept: Concept;
  selectedConcept: Concept | null;
  onSelectConcept: (concept: Concept) => void;
  onNavigateToParent: (parentName: string) => void;
  onViewPrerequisite?: (parentConcept: Concept, prereqName: string) => void;
  onAddPrerequisite?: (concept: Concept, prerequisiteName: string) => void;
  onRemovePrerequisite?: (concept: Concept, prerequisiteName: string) => void;
  conceptMap?: Map<string, Concept>;
}

const ConceptListItem: React.FC<ConceptListItemProps & { itemRef?: React.RefObject<HTMLDivElement | null> }> = ({
  concept,
  selectedConcept,
  onSelectConcept,
  onNavigateToParent,
  onViewPrerequisite,
  onAddPrerequisite,
  onRemovePrerequisite,
  conceptMap: map,
  itemRef,
}) => {
  const isSelected = selectedConcept?.id === concept.id;
  const hasLesson = Boolean(concept.lesson);

  // Get all prerequisite concepts (both existing and missing)
  const prerequisiteConcepts = React.useMemo(() => {
    if (!concept.prerequisites || concept.prerequisites.length === 0) {
      return [];
    }
    
    if (!map) {
      // If no conceptMap, show all as missing
      return concept.prerequisites.map(prereqName => ({
        id: `missing_${prereqName}`,
        name: prereqName,
        description: `Prerequisite for ${concept.name}`,
        parents: [],
        children: [],
        isAutoGenerated: true,
        isPrerequisite: true,
        isMissing: true,
      } as Concept & { isMissing: boolean }));
    }
    
    // Show all prerequisites, marking which ones are missing
    return concept.prerequisites.map(prereqName => {
      const existingPrereq = map.get(prereqName);
      if (existingPrereq) {
        // Prerequisite exists in graph
        return {
          ...existingPrereq,
          isPrerequisite: true,
          isMissing: false,
        } as Concept & { isMissing: boolean };
      } else {
        // Prerequisite is missing
        return {
          id: `missing_${prereqName}`,
          name: prereqName,
          description: `Prerequisite for ${concept.name}`,
          parents: [],
          children: [],
          isAutoGenerated: true,
          isPrerequisite: true,
          isMissing: true,
        } as Concept & { isMissing: boolean };
      }
    });
  }, [concept.prerequisites, map, concept.name]);

  const cardBaseClasses = 'p-4 border rounded-lg mb-3 transition-all duration-200 cursor-pointer';
  const cardStateClasses = isSelected
    ? 'border-indigo-500 dark:border-indigo-600 bg-indigo-50 dark:bg-indigo-900/30 shadow-md'
    : hasLesson
      ? 'border-emerald-400 dark:border-emerald-600 bg-emerald-50/70 dark:bg-emerald-900/20 hover:border-emerald-500 dark:hover:border-emerald-500 hover:shadow-md'
      : 'border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-gray-300 dark:hover:border-gray-600 hover:shadow-sm';

  return (
    <div>
      <div
        ref={itemRef}
        className={`${cardBaseClasses} ${cardStateClasses}`}
        onClick={() => onSelectConcept(concept)}
      >
        <ConceptName
          concept={concept}
          isEditing={false}
          editValues={{ name: concept.name }}
          onNameChange={() => { }}
          onStartEditing={() => { }}
          onCancelEdit={() => { }}
          onKeyDown={() => { }}
          nameInputRefs={{ current: {} }}
          onTitleClick={() => onSelectConcept(concept)}
        />
        <div className="mt-2">
          <ConceptDescription
            concept={concept}
            isEditing={false}
            editValues={{ description: concept.description }}
            onDescriptionChange={() => { }}
            onStartEditing={() => { }}
            onCancelEdit={() => { }}
            onKeyDown={() => { }}
            descriptionTextareaRefs={{ current: {} }}
            showFullContent={false}
          />
        </div>
        {concept.parents.length > 0 && (
          <div className="mt-3">
            <ConceptParents
              concept={concept}
              onNavigateToParent={onNavigateToParent}
            />
          </div>
        )}
        {hasLesson && (
          <div
            className={`mt-3 text-xs font-semibold uppercase tracking-wide ${isSelected ? 'text-indigo-600 dark:text-indigo-400' : 'text-emerald-600 dark:text-emerald-400'
              }`}
          >
            Lesson Available
          </div>
        )}
      </div>
      
      {/* Display prerequisites as sub-items */}
      {prerequisiteConcepts.length > 0 && (
        <PrerequisitesSubList
          prerequisites={prerequisiteConcepts}
          concept={concept}
          onSelectConcept={onSelectConcept}
          onNavigateToParent={onNavigateToParent}
          onAddPrerequisite={onAddPrerequisite}
          onRemovePrerequisite={onRemovePrerequisite}
          conceptMap={map}
          onViewPrerequisite={onViewPrerequisite}
        />
      )}
    </div>
  );
};

interface PrerequisitesSubListProps {
  prerequisites: (Concept & { isMissing?: boolean })[];
  concept: Concept;
  onSelectConcept: (concept: Concept) => void;
  onNavigateToParent: (parentName: string) => void;
  onAddPrerequisite?: (concept: Concept, prerequisiteName: string) => void;
  onRemovePrerequisite?: (concept: Concept, prerequisiteName: string) => void;
  conceptMap?: Map<string, Concept>;
  onViewPrerequisite?: (parentConcept: Concept, prereqName: string) => void;
}

const PrerequisitesSubList: React.FC<PrerequisitesSubListProps> = ({
  prerequisites,
  concept,
  onSelectConcept,
  onNavigateToParent,
  onAddPrerequisite,
  onRemovePrerequisite,
  conceptMap,
  onViewPrerequisite,
}) => {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div className="ml-6 mt-3 mb-4 space-y-2.5 border-l-2 border-orange-300 pl-4">
      <button
        type="button"
        onClick={(e) => {
          e.stopPropagation();
          setIsExpanded(!isExpanded);
        }}
        className="flex items-center gap-2 mb-1 w-full text-left hover:opacity-80 transition-opacity"
      >
        {isExpanded ? (
          <ChevronDown className="h-3 w-3 text-orange-700" />
        ) : (
          <ChevronRight className="h-3 w-3 text-orange-700" />
        )}
        <span className="text-xs font-semibold text-orange-700 uppercase tracking-wide">
          Prerequisites for {concept.name}
        </span>
        <span className="inline-flex items-center justify-center min-w-[1.25rem] h-4 px-1 text-xs font-medium text-orange-700 bg-orange-100 rounded-full">
          {(concept.prerequisites || []).length}
        </span>
      </button>

      {isExpanded && (
        <PrerequisiteList
          concept={concept}
          variant="list"
          conceptMap={conceptMap}
          onViewPrerequisite={(n: string) => onViewPrerequisite ? onViewPrerequisite(concept, n) : onNavigateToParent(n)}
          onAddPrerequisite={onAddPrerequisite ? (n: string) => onAddPrerequisite(concept, n) : undefined}
          onRemovePrerequisite={onRemovePrerequisite ? (n: string) => onRemovePrerequisite(concept, n) : undefined}
        />
      )}
    </div>
  );
};

interface ConceptListProps {
  concepts: Concept[];
  selectedConcept: Concept | null;
  onSelectConcept: (concept: Concept) => void;
  onNavigateToParent: (parentName: string) => void;
  onViewPrerequisite?: (parentConcept: Concept, prereqName: string) => void;
  onAddPrerequisite?: (concept: Concept, prerequisiteName: string) => void;
  onRemovePrerequisite?: (concept: Concept, prerequisiteName: string) => void;
  onLoadMoreLayers: () => void;
  onSummarizeLayer: (layer: number) => void;
  isLoading?: boolean;
  expandedLevels: Record<number, boolean>;
  onToggleLevel: (level: number) => void;
  levelRefs: Record<number, React.RefObject<HTMLDivElement | null>>;
  conceptMap?: Map<string, Concept>;
  graph?: ConceptGraph; // Graph to access layer goals
}

const ConceptListEmptyState: React.FC = () => (
  <div className="text-center py-12 bg-gray-50 dark:bg-gray-800 rounded-lg border-2 border-dashed border-gray-300 dark:border-gray-700">
    <p className="text-gray-500 dark:text-gray-400 text-lg mb-4">No concepts yet</p>
  </div>
);

interface ConceptLevelSectionProps {
  level: number;
  concepts: Concept[];
  goal?: string; // Goal for this layer
  selectedConcept: Concept | null;
  isExpanded: boolean;
  onToggle: () => void;
  onSelectConcept: (concept: Concept) => void;
  onNavigateToParent: (parentName: string) => void;
  onViewPrerequisite?: (parentConcept: Concept, prereqName: string) => void;
  onAddPrerequisite?: (concept: Concept, prerequisiteName: string) => void;
  onRemovePrerequisite?: (concept: Concept, prerequisiteName: string) => void;
  conceptRefs: Record<string, React.RefObject<HTMLDivElement | null>>;
  conceptMap?: Map<string, Concept>;
  sectionRef?: React.RefObject<HTMLDivElement | null>;
  graph?: ConceptGraph; // Graph to access layer data
}

const ConceptLevelSection: React.FC<ConceptLevelSectionProps> = ({
  level,
  concepts,
  goal,
  selectedConcept,
  isExpanded,
  onToggle,
  onSelectConcept,
  onNavigateToParent,
  onViewPrerequisite,
  onAddPrerequisite,
  onRemovePrerequisite,
  conceptRefs,
  conceptMap,
  sectionRef,
  graph,
}) => {
  const [isPracticeModalOpen, setIsPracticeModalOpen] = useState(false);
  
  // Automatically expand goal when layer is expanded
  const isGoalExpanded = isExpanded && goal;

  return (
    <div className="space-y-3" ref={sectionRef}>
      <div className="flex items-center justify-between border-b border-gray-200 dark:border-gray-700 pb-3">
        <button
          type="button"
          onClick={onToggle}
          className="flex items-center gap-3 text-left text-xl font-semibold text-gray-900 dark:text-gray-100 focus:outline-none flex-1"
        >
          <span className="flex h-9 w-9 items-center justify-center rounded-full bg-indigo-100 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 flex-shrink-0">
            {isExpanded ? <Minus size={18} /> : <Plus size={18} />}
          </span>
          <span className="flex items-center gap-2">
            <Layers size={20} className="text-indigo-600" />
            <span>Level {level + 1}</span>
            <span className="text-sm font-normal text-gray-500">
              ({concepts.length} concept{concepts.length !== 1 ? 's' : ''})
            </span>
          </span>
        </button>
      </div>
      {goal && isGoalExpanded && (
        <div className="w-full mb-1 p-4 bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 dark:from-indigo-900/20 dark:via-purple-900/20 dark:to-pink-900/20 border border-indigo-200 dark:border-indigo-700 rounded-lg shadow-sm">
          <div className="flex items-start gap-3">
            <div className="flex-shrink-0 mt-0.5">
              <div className="w-8 h-8 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-sm">
                <Target size={16} className="text-white" />
              </div>
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-2">
                <h4 className="text-sm font-semibold text-gray-900 dark:text-gray-100">Learning Goal</h4>
                <Info size={14} className="text-indigo-500 dark:text-indigo-400 flex-shrink-0" />
              </div>
              <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">{goal}</p>
            </div>
          </div>
        </div>
      )}

      {isExpanded && (
        <>
          <div className="space-y-2">
            {concepts.map(concept => (
              <ConceptListItem
                key={concept.id || concept.name}
                concept={concept}
                selectedConcept={selectedConcept}
                onSelectConcept={onSelectConcept}
                onNavigateToParent={onNavigateToParent}
                onViewPrerequisite={onViewPrerequisite}
                onAddPrerequisite={onAddPrerequisite}
                onRemovePrerequisite={onRemovePrerequisite}
                conceptMap={conceptMap}
                itemRef={conceptRefs[concept.id || concept.name]}
              />
            ))}
          </div>
          {/* Practice Button - Show for all levels */}
          {(() => {
            const layerData = graph?.layers?.get(level);
            const hasExistingExercises = layerData?.practiceExercises && layerData.practiceExercises.length > 0;
            
            return (
              <>
                <div className="pt-3 mt-3 border-t border-gray-200 dark:border-gray-700">
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      setIsPracticeModalOpen(true);
                    }}
                    className="w-full flex items-center justify-center gap-2 px-4 py-3 text-sm font-semibold text-white bg-indigo-600 dark:bg-indigo-500 hover:bg-indigo-700 dark:hover:bg-indigo-600 active:bg-indigo-800 dark:active:bg-indigo-700 rounded-lg transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 shadow-sm hover:shadow-md cursor-pointer"
                  >
                    <BookOpen size={16} />
                    <span>Level {level + 1} Final Review</span>
                  </button>
                </div>
                <LayerPracticeModal
                  isOpen={isPracticeModalOpen}
                  onClose={() => setIsPracticeModalOpen(false)}
                  concepts={concepts}
                  layerGoal={goal || `Practice exercises for Level ${level + 1}`}
                  layerNumber={level}
                  existingExercises={layerData?.practiceExercises}
                  graphId={graph?.id}
                />
              </>
            );
          })()}
        </>
      )}
    </div>
  )
};

const ConceptList: React.FC<ConceptListProps> = ({
  concepts,
  selectedConcept,
  onSelectConcept,
  onNavigateToParent,
  onViewPrerequisite,
  onAddPrerequisite,
  onRemovePrerequisite,
  onLoadMoreLayers,
  onSummarizeLayer,
  isLoading = false,
  expandedLevels,
  onToggleLevel,
  levelRefs,
  conceptMap,
  graph,
}) => {
  const conceptRefs = useMemo(() => {
    const refs: Record<string, React.RefObject<HTMLDivElement | null>> = {};
    concepts.forEach(concept => {
      refs[concept.id || concept.name] = React.createRef<HTMLDivElement>();
    });
    return refs;
  }, [concepts]);

  const levels = useConceptLevels(concepts, graph);

  useEffect(() => {
    const targetConcept = selectedConcept || concepts[0];
    if (!targetConcept) {
      return;
    }

    const ref = conceptRefs[targetConcept.id || targetConcept.name];
    if (ref?.current) {
      ref.current.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
  }, [conceptRefs, selectedConcept, concepts]);

  return (
    <div className="space-y-6">
      {levels.length === 0 ? (
        <ConceptListEmptyState />
      ) : (
        levels.map(({ level, concepts: levelConcepts, goal }) => (
          <ConceptLevelSection
            key={level}
            level={level}
            concepts={levelConcepts}
            goal={goal}
            selectedConcept={selectedConcept}
            isExpanded={expandedLevels[level] ?? false}
            onToggle={() => onToggleLevel(level)}
            onSelectConcept={onSelectConcept}
            onNavigateToParent={onNavigateToParent}
            onViewPrerequisite={onViewPrerequisite}
            onAddPrerequisite={onAddPrerequisite}
            onRemovePrerequisite={onRemovePrerequisite}
            conceptRefs={conceptRefs}
            conceptMap={conceptMap}
            sectionRef={levelRefs?.[level]}
            graph={graph}
          />
        ))
      )}

      {levels.length > 0 && (
        <div className="flex justify-center pt-4 border-t border-gray-200 dark:border-gray-700">
          <button
            onClick={onLoadMoreLayers}
            disabled={isLoading}
            className="inline-flex items-center gap-2 px-6 py-3 bg-indigo-600 dark:bg-indigo-500 text-white rounded-lg hover:bg-indigo-700 dark:hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-200 font-medium disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isLoading ? (
              <>
                <Loader2 size={18} className="animate-spin" />
                Loading...
              </>
            ) : (
              <>
                Load Next Level
              </>
            )}
          </button>
        </div>
      )}
    </div>
  );
};

export default ConceptList;