import { useMemo } from 'react';
import { Concept, ConceptGraph } from '../types';

export interface ConceptLevelGroup {
  level: number;
  concepts: Concept[];
  goal?: string; // Goal for this layer
}

export const computeConceptLevels = (concepts: Concept[], graph?: ConceptGraph): ConceptLevelGroup[] => {
  // Find seed concept
  const seedConcept = concepts.find(c => c.isSeed) || concepts.find(c => 
    c.parents.length === 0 || (c.parents.length === 1 && c.parents[0] === c.name)
  );
  
  if (!seedConcept) {
    // No seed concept - return empty levels
    return [];
  }

  // Find ALL top-level concepts (concepts with seedConcept as their sole parent)
  // All top-level concepts are automatically levels - no pattern matching needed
  const levelConcepts = concepts.filter(c => 
    c.parents.length === 1 && 
    c.parents[0] === seedConcept.name &&
    c.name !== seedConcept.name // Exclude seed concept itself
  );

  // Sort level concepts by sequence to maintain order
  levelConcepts.sort((a, b) => {
    const seqA = a.sequence ?? Number.MAX_SAFE_INTEGER;
    const seqB = b.sequence ?? Number.MAX_SAFE_INTEGER;
    if (seqA !== seqB) return seqA - seqB;
    return a.name.localeCompare(b.name);
  });

  // Build level groups - use index as level number (0-based for internal use)
  return levelConcepts.map((levelConcept, index) => {
    // Get concepts that are children of this level concept
    const levelConceptsList = concepts.filter(c => 
      levelConcept.children.includes(c.name)
    );
    
    // Filter out prerequisites - they will be displayed as sub-items
    const nonPrerequisiteConcepts = levelConceptsList.filter(concept => {
      if (concept.isPrerequisite !== undefined) {
        return !concept.isPrerequisite;
      }
      // Fallback: check if auto-generated and referenced in another concept's prerequisites
      if (!concept.isAutoGenerated) {
        return true;
      }
      return !concepts.some(c => 
        c.prerequisites && c.prerequisites.includes(concept.name)
      );
    });
    
    // Sort by sequence
    const sortedConcepts = nonPrerequisiteConcepts.sort((a, b) => {
      const seqA = a.sequence ?? Number.MAX_SAFE_INTEGER;
      const seqB = b.sequence ?? Number.MAX_SAFE_INTEGER;
      if (seqA !== seqB) return seqA - seqB;
      return a.name.localeCompare(b.name);
    });
    
    // Use index as level number (0-based for internal use, or 1-based for display)
    const level = index; // Or index + 1 if you want 1-based levels
    
    // Get goal from level concept's goal property
    const goal = levelConcept.goal;
    
    return {
      level,
      concepts: sortedConcepts,
      goal,
    };
  });
};

export const useConceptLevels = (concepts: Concept[], graph?: ConceptGraph): ConceptLevelGroup[] =>
  useMemo(() => computeConceptLevels(concepts, graph), [concepts, graph]);


