import { getFirestore } from '@almadar/server';
import { createLogger } from '@almadar/logger';
import { callLLM, extractJSONObject, AI_LLM } from './llm';
import type { ConceptPersonaDTO } from '@kflow-academy/shared';

const log = createLogger('kflow:server:conceptPersonaService');

const MAX_HISTORY_TURNS = 8;
const WIKI_UA = 'KFlowAcademy/1.0 (https://kflow.academy)';
const WIKI_TIMEOUT_MS = 6000;

interface WikiPage {
  missing?: '' | boolean;
  title?: string;
  description?: string;
  extract?: string;
  thumbnail?: { source?: string };
}
interface WikiQueryResponse {
  query?: { pages?: Record<string, WikiPage> };
}

interface CachedPersona {
  persona: ConceptPersonaDTO;
  greeting: string;
  cachedAt: number;
}

function cacheKey(conceptLabel: string): string {
  return conceptLabel.toLowerCase().replace(/[^a-z0-9_-]+/g, '_').slice(0, 180) || 'concept';
}

/**
 * Look up the originator on Wikipedia (one redirect-resolved call) for a verified one-line
 * bio + a real Wikimedia Commons portrait. Returns {} on any miss — caller keeps the
 * LLM description and renders a monogram avatar. Wikimedia requires a descriptive UA.
 */
async function fetchWikiPersona(name: string): Promise<{ description?: string; portraitUrl?: string }> {
  const title = encodeURIComponent(name.trim());
  const url =
    'https://en.wikipedia.org/w/api.php?action=query&format=json&redirects=1' +
    '&prop=pageimages|description|extracts&explaintext=1&exsentences=1' +
    '&piprop=thumbnail&pithumbsize=240&titles=' +
    title;
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), WIKI_TIMEOUT_MS);
  try {
    const res = await fetch(url, { headers: { 'User-Agent': WIKI_UA }, signal: ctrl.signal });
    if (!res.ok) return {};
    const data = (await res.json()) as WikiQueryResponse;
    const pages = data.query?.pages;
    if (!pages) return {};
    const page = Object.values(pages)[0];
    if (!page || page.missing !== undefined) return {};
    return {
      description: page.description ?? page.extract,
      portraitUrl: page.thumbnail?.source,
    };
  } catch (e) {
    log.debug('fetchWikiPersona miss', { name, error: e instanceof Error ? e.message : String(e) });
    return {};
  } finally {
    clearTimeout(timer);
  }
}

/**
 * On-the-fly AI persona for a concept: the historically credited originator/pioneer,
 * generated by the cheap MoE (qwen3-30b-a3b) then enriched + fact-checked via Wikipedia
 * (real portrait + verified bio). Cached per concept so identity is stable and the external
 * calls happen at most once per concept.
 */
export async function generatePersona(
  conceptLabel: string,
): Promise<{ persona: ConceptPersonaDTO; greeting: string }> {
  const ref = getFirestore().collection('concept-personas').doc(cacheKey(conceptLabel));
  const cached = await ref.get();
  if (cached.exists) {
    const c = cached.data() as CachedPersona;
    return { persona: c.persona, greeting: c.greeting };
  }

  const resp = await callLLM({
    provider: AI_LLM.provider,
    model: AI_LLM.replyModel,
    temperature: 0.3,
    maxTokens: 220,
    systemPrompt:
      'You identify the single most historically credited originator or pioneer of a learning ' +
      'concept, then greet a learner in their voice. Reply ONLY with compact JSON: ' +
      '{"name":<full canonical name as it would title a Wikipedia article, e.g. "Isaac Newton">,' +
      '"description":<one sentence, max ~20 words: who they are + key contribution>,' +
      '"greeting":<one warm first-person sentence, in character, mentioning the concept>}. ' +
      'If no single person is credited, pick the most iconic figure associated with it. ' +
      'Never invent a fictional person.',
    userPrompt: `Concept: ${conceptLabel}`,
  });
  const obj = extractJSONObject(resp.content);
  const name = typeof obj.name === 'string' && obj.name.trim() ? obj.name.trim() : conceptLabel;
  const llmDescription =
    typeof obj.description === 'string' && obj.description.trim()
      ? obj.description.trim()
      : `A pioneer associated with ${conceptLabel}.`;
  const greeting =
    typeof obj.greeting === 'string' && obj.greeting.trim()
      ? obj.greeting.trim()
      : `Hello — I'm ${name}. Ask me anything about ${conceptLabel}.`;

  const wiki = await fetchWikiPersona(name);
  const persona: ConceptPersonaDTO = {
    name,
    description: wiki.description ?? llmDescription,
    portraitUrl: wiki.portraitUrl,
  };

  const result = { persona, greeting };
  await ref.set({ ...result, cachedAt: Date.now() }).catch((e) =>
    log.warn('concept-persona cache write failed', { error: e instanceof Error ? e.message : String(e) }),
  );
  log.debug('generatePersona', { conceptLabel, name, hasPortrait: !!persona.portraitUrl });
  return result;
}

/**
 * Reply in the persona's voice, grounded in the concept + recent transcript. The persona
 * object is supplied by the caller (held client-side) so identity is stable within a chat.
 */
export async function replyAsPersona(
  persona: ConceptPersonaDTO,
  conceptLabel: string,
  history: { role: 'user' | 'assistant'; content: string }[],
  userMessage: string,
): Promise<string> {
  const trimmed = history
    .slice(-MAX_HISTORY_TURNS)
    .map((m) => `${m.role === 'user' ? 'Learner' : persona.name}: ${m.content}`)
    .join('\n');
  const resp = await callLLM({
    provider: AI_LLM.provider,
    model: AI_LLM.replyModel,
    temperature: 0.6,
    maxTokens: 320,
    systemPrompt:
      `You are ${persona.name}. ${persona.description} ` +
      `A learner is studying "${conceptLabel}". Reply in first person, in character, ` +
      `warmly and concisely (max ~120 words). Ground the answer in the concept and stay ` +
      `factual; if you are unsure, say so plainly. Do not break character.`,
    userPrompt: trimmed ? `${trimmed}\nLearner: ${userMessage}` : userMessage,
  });
  const content = typeof resp.content === 'string' ? resp.content.trim() : '';
  return content || `I'm not certain — let's explore ${conceptLabel} together.`;
}
