import { createLogger } from '@almadar/logger';
import { callLLM, extractJSONObject, AI_LLM } from './llm';
import type { JsonValue } from '@almadar/core';
import type { ConceptPersonaDTO } from '@kflow-academy/shared';

const log = createLogger('kflow:server:conceptPersonaService');

const MAX_HISTORY_TURNS = 8;

/**
 * On-the-fly AI persona for a concept: the historically credited originator/pioneer,
 * generated by the cheap MoE (qwen3-30b-a3b). No registry, no scheduler — the persona
 * is created when a learner opens the chat and held client-side for the session.
 */
export async function generatePersona(conceptLabel: string): Promise<{ persona: ConceptPersonaDTO; greeting: string }> {
  const resp = await callLLM({
    provider: AI_LLM.provider,
    model: AI_LLM.replyModel,
    temperature: 0.3,
    maxTokens: 220,
    systemPrompt:
      'You identify the single most historically credited originator or pioneer of a learning ' +
      'concept, then greet a learner in their voice. Reply ONLY with compact JSON: ' +
      '{"name":<full name>,"description":<one sentence, max ~20 words: who they are + key contribution>,' +
      '"greeting":<one warm first-person sentence, in character, mentioning the concept>}. ' +
      'If no single person is credited, pick the most iconic figure associated with it. ' +
      'Never invent a fictional person.',
    userPrompt: `Concept: ${conceptLabel}`,
  });
  const obj = extractJSONObject(resp.content);
  const name = typeof obj.name === 'string' && obj.name.trim() ? obj.name.trim() : conceptLabel;
  const description = typeof obj.description === 'string' && obj.description.trim()
    ? obj.description.trim()
    : `A pioneer associated with ${conceptLabel}.`;
  const greeting = typeof obj.greeting === 'string' && obj.greeting.trim()
    ? obj.greeting.trim()
    : `Hello — I'm ${name}. Ask me anything about ${conceptLabel}.`;
  log.debug('generatePersona', { conceptLabel, name });
  return { persona: { name, description }, greeting };
}

/**
 * Reply in the persona's voice, grounded in the concept + recent transcript. The persona
 * object is supplied by the caller (held client-side) so identity is stable within a chat.
 */
export async function replyAsPersona(
  persona: ConceptPersonaDTO,
  conceptLabel: string,
  history: { role: 'user' | 'assistant'; content: string }[],
  userMessage: string,
): Promise<string> {
  const trimmed = history.slice(-MAX_HISTORY_TURNS)
    .map((m) => `${m.role === 'user' ? 'Learner' : persona.name}: ${m.content}`)
    .join('\n');
  const resp = await callLLM({
    provider: AI_LLM.provider,
    model: AI_LLM.replyModel,
    temperature: 0.6,
    maxTokens: 320,
    systemPrompt:
      `You are ${persona.name}. ${persona.description} ` +
      `A learner is studying "${conceptLabel}". Reply in first person, in character, ` +
      `warmly and concisely (max ~120 words). Ground the answer in the concept and stay ` +
      `factual; if you are unsure, say so plainly. Do not break character.`,
    userPrompt: trimmed ? `${trimmed}\nLearner: ${userMessage}` : userMessage,
  });
  const content = typeof (resp as { content?: JsonValue }).content === 'string'
    ? (resp as { content: string }).content.trim()
    : '';
  return content || `I'm not certain — let's explore ${conceptLabel} together.`;
}
