/**
 * Knowledge Graph Service
 * 
 * Works exclusively with NodeBasedKnowledgeGraph format.
 * Converts StoredConceptGraph directly to NodeBasedKnowledgeGraph.
 * 
 * Note: Embeddings and NetworkX conversions remain in Python service.
 */

import type { 
  NodeBasedKnowledgeGraph,
  GraphNode,
  Relationship as NodeBasedRelationship,
} from '../types/nodeBasedKnowledgeGraph';
import type { StoredConceptGraph } from './graphService';
import type { LearningGoal } from '../types/goal';
import { getFirestore } from '../config/firebaseAdmin';
import {
  createGraphNode,
  createRelationship,
  generateNodeId,
} from '../types/nodeBasedKnowledgeGraph';

/**
 * Options for converting StoredConceptGraph to NodeBasedKnowledgeGraph
 */
export interface ConvertToNodeBasedOptions {
  includeLayers?: boolean;        // Convert layers to nodes (default: true)
  includeLessons?: boolean;       // Extract lessons to nodes (default: true)
  includeMetadata?: boolean;      // Extract metadata to nodes (default: true)
  includeFlashCards?: boolean;    // Extract flash cards to nodes (default: true)
  learningGoal?: LearningGoal | {  // Optional learning goal (full object or just title/description)
    title: string;
    description: string;
  };
}

/**
 * Result of conversion to node-based structure
 */
export interface NodeBasedConversionResult {
  nodeBasedGraph: NodeBasedKnowledgeGraph;
  stats: {
    nodesCreated: number;
    relationshipsCreated: number;
    layersConverted: number;
    goalsConverted: number;
    lessonsExtracted: number;
    metadataExtracted: number;
  };
}

/**
 * Convert StoredConceptGraph directly to NodeBasedKnowledgeGraph
 */
export function convertStoredConceptGraphToNodeBased(
  conceptGraph: StoredConceptGraph,
  options: ConvertToNodeBasedOptions = {}
): NodeBasedConversionResult {
  const {
    // Note: includeLayers is no longer used - layers are always inferred from top-level concepts
    includeLessons = true,
    includeMetadata = true,
    includeFlashCards = true,
    learningGoal,
  } = options;

  const nodes: Record<string, GraphNode> = {};
  const relationships: NodeBasedRelationship[] = [];
  const nodeTypes: NodeBasedKnowledgeGraph['nodeTypes'] = {
    Graph: [],
    Concept: [],
    Layer: [],
    LearningGoal: [],
    Milestone: [],
    PracticeExercise: [],
    Lesson: [],
    ConceptMetadata: [],
    GraphMetadata: [],
    FlashCard: [],
  };

  let layersConverted = 0;
  let goalsConverted = 0;
  let lessonsExtracted = 0;
  let metadataExtracted = 0;

  const graphId = conceptGraph.id;

  // Note: We do NOT create a Graph node here - the graph identity is implicit
  // This matches the structure generated by MentorGoalFormSteps/progressiveExpand

  // Find seed concept name to use as seedConceptId in converted graph
  // The original seedConceptId might be a UUID, but we use conceptName as node ID
  let convertedSeedConceptId = conceptGraph.seedConceptId;
  for (const [conceptName, concept] of Object.entries(conceptGraph.concepts)) {
    // Check if this concept matches the seed (by id, name, or isSeed flag)
    if (concept.isSeed || concept.id === conceptGraph.seedConceptId || conceptName === conceptGraph.seedConceptId) {
      convertedSeedConceptId = conceptName; // Use conceptName as the node ID
      break;
    }
  }

  // 2. Convert concepts to Concept nodes
  for (const [conceptName, concept] of Object.entries(conceptGraph.concepts)) {
    const conceptNodeId = conceptName; // Use concept name as ID
    
    // Update seedConcept with learning goal if missing
    let conceptGoal = concept.goal;
    if (learningGoal && (concept.isSeed || conceptName === conceptGraph.seedConceptId || concept.id === conceptGraph.seedConceptId) && !conceptGoal) {
      const goalTitle = typeof learningGoal === 'object' && 'title' in learningGoal 
        ? learningGoal.title 
        : (learningGoal as any).title || '';
      const goalDescription = typeof learningGoal === 'object' && 'description' in learningGoal
        ? learningGoal.description
        : (learningGoal as any).description || '';
      conceptGoal = `${goalTitle}: ${goalDescription}`;
    }
    
    // Determine layer number for this concept
    // Use concept.layer if available, otherwise infer from structure
    let conceptLayer = concept.layer !== undefined ? concept.layer : 0;
    
    // Create Concept node with layer property
    const conceptNode = createGraphNode(
      conceptNodeId,
      'Concept',
      {
        id: conceptNodeId,
        name: concept.name,
        description: concept.description,
        sequence: concept.sequence,
        focus: concept.focus,
        isSeed: concept.isSeed,
        isAutoGenerated: concept.isAutoGenerated,
        isPrerequisite: concept.isPrerequisite,
        goal: conceptGoal,
        layer: conceptLayer, // Store layer number in properties
      },
      conceptGraph.createdAt,
      conceptGraph.updatedAt
    );
    nodes[conceptNodeId] = conceptNode;
    nodeTypes.Concept.push(conceptNodeId);

    // Note: We do NOT create Graph → containsConcept relationships
    // In the new structure, concepts are linked to Layers via containsConcept/belongsToLayer
    // and the graph structure is implicit (no Graph node)

    // Extract lesson to Lesson node if enabled
    if (includeLessons && concept.lesson) {
      const lessonNodeId = generateNodeId('Lesson', { conceptId: conceptNodeId });
      const lessonNode = createGraphNode(
        lessonNodeId,
        'Lesson',
        {
          id: lessonNodeId,
          content: concept.lesson,
          generatedAt: conceptGraph.updatedAt,
          model: conceptGraph.model,
        },
        conceptGraph.updatedAt
      );
      nodes[lessonNodeId] = lessonNode;
      nodeTypes.Lesson.push(lessonNodeId);
      relationships.push(
        createRelationship(conceptNodeId, lessonNodeId, 'hasLesson', 'forward', 1.0, {
          extractedFrom: 'concept_structure',
          confidence: 1.0,
        })
      );
      lessonsExtracted++;
    }

    // Extract metadata to ConceptMetadata node if enabled
    if (includeMetadata) {
      // Infer metadata from concept
      const metadata = inferConceptMetadata(concept, conceptGraph);
      if (metadata) {
        const metadataNodeId = generateNodeId('ConceptMetadata', { conceptId: conceptNodeId });
        const metadataNode = createGraphNode(
          metadataNodeId,
          'ConceptMetadata',
          {
            id: metadataNodeId,
            difficulty: metadata.difficulty,
            timeEstimate: metadata.timeEstimate,
            domain: metadata.domain,
            tags: metadata.tags,
            resourceLinks: metadata.resourceLinks,
          },
          conceptGraph.updatedAt
        );
        nodes[metadataNodeId] = metadataNode;
        nodeTypes.ConceptMetadata.push(metadataNodeId);
        relationships.push(
          createRelationship(conceptNodeId, metadataNodeId, 'hasMetadata', 'forward', 1.0, {
            extractedFrom: 'concept_metadata',
            confidence: 1.0,
          })
        );
        metadataExtracted++;
      }
    }

    // Extract flash cards to FlashCard nodes if enabled
    if (includeFlashCards && concept.flash && concept.flash.length > 0) {
      concept.flash.forEach((flashCard, index) => {
        const flashCardNodeId = generateNodeId('FlashCard', {
          conceptId: conceptNodeId,
          index,
        });
        const flashCardNode = createGraphNode(
          flashCardNodeId,
          'FlashCard',
          {
            id: flashCardNodeId,
            front: flashCard.front,
            back: flashCard.back,
          },
          conceptGraph.updatedAt
        );
        nodes[flashCardNodeId] = flashCardNode;
        nodeTypes.FlashCard.push(flashCardNodeId);
        relationships.push(
          createRelationship(conceptNodeId, flashCardNodeId, 'hasFlashCard', 'forward', 1.0, {
            extractedFrom: 'concept_structure',
            confidence: 1.0,
          })
        );
      });
    }

    // Create parent/child relationships
    for (const parentName of concept.parents || []) {
      if (parentName in conceptGraph.concepts) {
        relationships.push(
          createRelationship(conceptNodeId, parentName, 'hasParent', 'forward', 1.0, {
            extractedFrom: 'concept_structure',
            confidence: 1.0,
          })
        );
        relationships.push(
          createRelationship(parentName, conceptNodeId, 'hasChild', 'forward', 1.0, {
            extractedFrom: 'concept_structure',
            confidence: 1.0,
          })
        );
      }
    }

    // Create prerequisite relationships
    for (const prereqName of concept.prerequisites || []) {
      if (prereqName in conceptGraph.concepts) {
        relationships.push(
          createRelationship(conceptNodeId, prereqName, 'hasPrerequisite', 'forward', 0.9, {
            extractedFrom: 'prerequisites',
            confidence: 0.9,
          })
        );
        relationships.push(
          createRelationship(prereqName, conceptNodeId, 'isPrerequisiteOf', 'forward', 0.9, {
            extractedFrom: 'prerequisites',
            confidence: 0.9,
          })
        );
      }
    }
  }

  // 3. Infer layer structure from concepts and create Layer nodes
  // 
  // Layer Model (matching MentorGoalFormSteps / progressiveExpand output):
  // - Seed concept has layer: 1 (same as Layer 1 concepts)
  // - Top-level concepts (sole parent = seed) define layer boundaries
  // - All children of a top-level concept belong to the same layer
  // - Layer 1 = seed + first top-level concept + its children
  // - Layer 2 = second top-level concept + its children (if exists)
  //
  const seedConceptNodeId = convertedSeedConceptId;
  
  // Build a map of concept node IDs to their inferred layer numbers
  const conceptLayerMap = new Map<string, number>();
  
  // Step 1: Find all top-level concepts (concepts whose SOLE parent is the seed)
  // These define layer boundaries
  const topLevelConcepts: string[] = [];
  
  for (const [conceptId, conceptNode] of Object.entries(nodes)) {
    if (conceptNode.type !== 'Concept') continue;
    if (conceptNode.properties?.isSeed) continue; // Skip seed itself
    
    // Find all hasParent relationships for this concept
    const parentRels = relationships.filter(
      r => r.source === conceptId && r.type === 'hasParent'
    );
    
    // Check if sole parent is the seed concept
    if (parentRels.length === 1 && parentRels[0].target === seedConceptNodeId) {
      topLevelConcepts.push(conceptId);
    }
  }
  
  // Step 2: Sort top-level concepts by sequence property
  // Each top-level concept defines a layer boundary
  const sortedTopLevelConcepts = [...topLevelConcepts].sort((a, b) => {
    const seqA = nodes[a]?.properties?.sequence ?? Infinity;
    const seqB = nodes[b]?.properties?.sequence ?? Infinity;
    return seqA - seqB;
  });
  
  console.log(`[convertStoredConceptGraphToNodeBased] Found ${sortedTopLevelConcepts.length} top-level concepts (sorted by sequence):`, 
    sortedTopLevelConcepts.map(id => ({ id, sequence: nodes[id]?.properties?.sequence })));
  
  // Set seed concept to layer 1 (not 0!)
  if (seedConceptNodeId && nodes[seedConceptNodeId]) {
    conceptLayerMap.set(seedConceptNodeId, 1);
    nodes[seedConceptNodeId].properties.layer = 1;
  }
  
  // Step 3: Build a map from top-level concept to its layer number
  const topLevelToLayerMap = new Map<string, number>();
  sortedTopLevelConcepts.forEach((topLevelConceptId, index) => {
    const layerNum = index + 1; // Layer 1, 2, 3, ...
    topLevelToLayerMap.set(topLevelConceptId, layerNum);
    
    // Assign the top-level concept itself to its layer
    conceptLayerMap.set(topLevelConceptId, layerNum);
    if (nodes[topLevelConceptId]) {
      nodes[topLevelConceptId].properties.layer = layerNum;
    }
  });
  
  // Step 4: Assign concepts to layers based on their parents
  // A concept belongs to a layer if the top-level concept is ONE OF its parents
  for (const [conceptId, conceptNode] of Object.entries(nodes)) {
    if (conceptNode.type !== 'Concept') continue;
    if (conceptNode.properties?.isSeed) continue; // Skip seed (already assigned)
    if (topLevelToLayerMap.has(conceptId)) continue; // Skip top-level concepts (already assigned)
    
    // Find all hasParent relationships for this concept
    const parentRels = relationships.filter(
      r => r.source === conceptId && r.type === 'hasParent'
    );
    
    // Find which top-level concept(s) this concept has as a parent
    let assignedLayerNum: number | null = null;
    
    for (const parentRel of parentRels) {
      const parentId = parentRel.target;
      
      // Check if this parent is a top-level concept
      if (topLevelToLayerMap.has(parentId)) {
        const parentLayerNum = topLevelToLayerMap.get(parentId)!;
        // If multiple top-level parents, use the one with the lowest layer number
        if (assignedLayerNum === null || parentLayerNum < assignedLayerNum) {
          assignedLayerNum = parentLayerNum;
        }
      }
    }
    
    // Assign concept to the layer of its top-level parent (or default to 1)
    const layerNum = assignedLayerNum ?? 1;
    conceptLayerMap.set(conceptId, layerNum);
    conceptNode.properties.layer = layerNum;
  }
  
  // Log layer assignments
  sortedTopLevelConcepts.forEach((topLevelConceptId, index) => {
    const layerNum = index + 1;
    const conceptsInLayer = Array.from(conceptLayerMap.entries())
      .filter(([_, l]) => l === layerNum)
      .map(([id, _]) => id);
    console.log(`[convertStoredConceptGraphToNodeBased] Layer ${layerNum}: ${conceptsInLayer.length} concepts (top-level: ${topLevelConceptId})`);
  });
  
  // Step 5: Handle any remaining concepts not assigned through parent relationships
  // (These are concepts that don't have any top-level concept as a parent)
  for (const [conceptNodeId, conceptNode] of Object.entries(nodes)) {
    if (conceptNode.type === 'Concept' && !conceptLayerMap.has(conceptNodeId)) {
      // Default to layer 1
      conceptLayerMap.set(conceptNodeId, 1);
      conceptNode.properties.layer = 1;
      console.log(`[convertStoredConceptGraphToNodeBased] Concept ${conceptNodeId} has no top-level parent, defaulting to Layer 1`);
    }
  }
  
  // Step 6: Group concepts by layer number (including seed which is now layer 1)
  const conceptsByLayer = new Map<number, string[]>();
  for (const [conceptNodeId, layerNum] of conceptLayerMap.entries()) {
    if (!conceptsByLayer.has(layerNum)) {
      conceptsByLayer.set(layerNum, []);
    }
    conceptsByLayer.get(layerNum)!.push(conceptNodeId);
  }
  
  console.log(`[convertStoredConceptGraphToNodeBased] Concepts by layer:`, 
    Array.from(conceptsByLayer.entries()).map(([l, ids]) => `Layer ${l}: ${ids.length} concepts`));
  
  // Create Layer nodes for each layer (all concepts now have layer >= 1)
  const layerNumbers = Array.from(conceptsByLayer.keys()).sort((a, b) => a - b);
  for (let i = 0; i < layerNumbers.length; i++) {
    const layerNumber = layerNumbers[i];
    const layerConceptIds = conceptsByLayer.get(layerNumber) || [];
    
    // Skip if no concepts in this layer
    if (layerConceptIds.length === 0) continue;
    
    const layerNodeId = generateNodeId('Layer', {
      graphId,
      layerNumber,
    });
    
    // Find the top-level concept for this layer using our mapping
    // (sortedTopLevelConcepts[layerNumber - 1] gives us the top-level concept for this layer)
    const topLevelConceptInLayer = sortedTopLevelConcepts[layerNumber - 1];
    
    // Get layer name and goal from top-level concepts only
    // (Do NOT use old conceptGraph.layers data)
    let layerName = `Level ${layerNumber}`;
    let layerGoal = '';
    
    // Priority 1: Get name and goal from top-level concept
    if (topLevelConceptInLayer && nodes[topLevelConceptInLayer]) {
      const topLevelNode = nodes[topLevelConceptInLayer];
      // Use top-level concept's name (e.g., "Foundation")
      if (topLevelNode.properties?.name) {
        layerName = topLevelNode.properties.name;
      }
      // Use top-level concept's goal
      if (topLevelNode.properties?.goal) {
        layerGoal = topLevelNode.properties.goal;
      }
    }
    
    // Priority 2: Fallback to first concept's goal
    if (!layerGoal) {
      const firstConceptId = layerConceptIds[0];
      if (firstConceptId && nodes[firstConceptId]) {
        layerGoal = nodes[firstConceptId].properties?.goal || '';
      }
    }
    
    console.log(`[convertStoredConceptGraphToNodeBased] Creating Layer ${layerNumber}: name="${layerName}", goal="${layerGoal?.substring(0, 50)}..."`);
    
    // Create Layer node
    const layerNode = createGraphNode(
      layerNodeId,
      'Layer',
      {
        id: layerNodeId,
        layerNumber,
        goal: layerGoal,
        name: layerName,
        createdAt: conceptGraph.createdAt,
      },
      conceptGraph.createdAt
    );
    nodes[layerNodeId] = layerNode;
    nodeTypes.Layer.push(layerNodeId);
    
    // Create relationship: SeedConcept → hasLayer → Layer
    // (This matches the structure in graphA where the seed concept links to all layers)
    if (seedConceptNodeId) {
      relationships.push(
        createRelationship(seedConceptNodeId, layerNodeId, 'hasLayer', 'forward', 1.0, {
          extractedFrom: 'concept_structure',
          confidence: 1.0,
        })
      );
    }
    
    // Create sequence relationships between layers
    if (i > 0) {
      const prevLayerNumber = layerNumbers[i - 1];
      const prevLayerNodeId = generateNodeId('Layer', {
        graphId,
        layerNumber: prevLayerNumber,
      });
      
      if (nodes[prevLayerNodeId]) {
        relationships.push(
          createRelationship(prevLayerNodeId, layerNodeId, 'precedesLayer', 'forward', 1.0, {
            extractedFrom: 'concept_structure',
            confidence: 1.0,
          })
        );
        relationships.push(
          createRelationship(layerNodeId, prevLayerNodeId, 'followsLayer', 'backward', 1.0, {
            extractedFrom: 'concept_structure',
            confidence: 1.0,
          })
        );
      }
    }
    
    // Create relationships: Layer → containsConcept → Concept and Concept → belongsToLayer → Layer
    for (const conceptId of layerConceptIds) {
      if (nodes[conceptId]) {
        relationships.push(
          createRelationship(layerNodeId, conceptId, 'containsConcept', 'forward', 1.0, {
            extractedFrom: 'concept_structure',
            confidence: 1.0,
          })
        );
        relationships.push(
          createRelationship(conceptId, layerNodeId, 'belongsToLayer', 'backward', 1.0, {
            extractedFrom: 'concept_structure',
            confidence: 1.0,
          })
        );
      }
    }
    
    layersConverted++;
  }

  // 4. Generate and add GraphMetadata node if enabled
  // Note: GraphA doesn't have GraphMetadata, but we keep it for backward compatibility
  // We just don't create a relationship from graphId since there's no Graph node
  if (includeMetadata) {
    const graphMetadata = generateGraphLevelMetadata(nodes, relationships);
    const metadataNodeId = generateNodeId('GraphMetadata', { graphId });
    const metadataNode = createGraphNode(
      metadataNodeId,
      'GraphMetadata',
      {
        id: metadataNodeId,
        totalConcepts: graphMetadata.totalConcepts,
        totalRelationships: graphMetadata.totalRelationships,
        averageDifficulty: graphMetadata.averageDifficulty,
        estimatedTotalTime: graphMetadata.estimatedTotalTime,
        domains: graphMetadata.domains,
        lastEmbeddingUpdate: graphMetadata.lastEmbeddingUpdate,
      },
      conceptGraph.updatedAt
    );
    nodes[metadataNodeId] = metadataNode;
    nodeTypes.GraphMetadata.push(metadataNodeId);
    // Note: No relationship to graphId since there's no Graph node
    // Metadata is kept for informational purposes
    metadataExtracted++;
  }

  // 5. Convert LearningGoal to nodes if learningGoal is provided
  if (learningGoal && seedConceptNodeId) {
    // Check if we have a full LearningGoal object or just title/description
    const isFullLearningGoal = 'id' in learningGoal && 'type' in learningGoal;
    
    if (isFullLearningGoal) {
      // Use convertLearningGoalToNodes for full conversion (includes milestones)
      const goalConversion = convertLearningGoalToNodes(
        graphId,
        learningGoal as LearningGoal,
        { nodes, nodeTypes, relationships } as NodeBasedKnowledgeGraph,
        seedConceptNodeId  // Pass seedConceptId for proper relationship
      );
      
      // Add the nodes and relationships from goal conversion
      for (const goalNode of goalConversion.nodes) {
        nodes[goalNode.id] = goalNode;
        const typeArray = nodeTypes[goalNode.type as keyof typeof nodeTypes];
        if (typeArray) {
          typeArray.push(goalNode.id);
        }
      }
      relationships.push(...goalConversion.relationships);
      goalsConverted = goalConversion.nodes.filter(n => n.type === 'LearningGoal').length;
    } else {
      // Create a basic LearningGoal node from title/description only
      const goalNodeId = generateNodeId('LearningGoal', { graphId, index: 0 });
      const goalNode = createGraphNode(
        goalNodeId,
        'LearningGoal',
        {
          id: goalNodeId,
          title: learningGoal.title,
          description: learningGoal.description,
          createdAt: conceptGraph.createdAt,
          updatedAt: conceptGraph.updatedAt,
        },
        conceptGraph.createdAt,
        conceptGraph.updatedAt
      );
      nodes[goalNodeId] = goalNode;
      nodeTypes.LearningGoal.push(goalNodeId);
      // Create relationship: SeedConcept → belongsToGoal → LearningGoal
      // (Matches graphA structure)
      relationships.push(
        createRelationship(seedConceptNodeId, goalNodeId, 'belongsToGoal', 'forward', 1.0, {
          extractedFrom: 'learning_goal',
          confidence: 1.0,
        })
      );
      goalsConverted = 1;
    }
  }

  // Create the node-based graph
  // Use convertedSeedConceptId which uses conceptName as node ID (not UUID)
  const nodeBasedGraph: NodeBasedKnowledgeGraph = {
    id: graphId,
    seedConceptId: convertedSeedConceptId,
    createdAt: conceptGraph.createdAt,
    updatedAt: conceptGraph.updatedAt,
    model: conceptGraph.model,
    goalFocused: conceptGraph.goalFocused,
    difficulty: conceptGraph.difficulty,
    focus: conceptGraph.focus,
    name: conceptGraph.focus || conceptGraph.name || conceptGraph.id,
    nodes,
    nodeTypes,
    relationships,
  };

  return {
    nodeBasedGraph,
    stats: {
      nodesCreated: Object.keys(nodes).length,
      relationshipsCreated: relationships.length,
      layersConverted,
      goalsConverted,
      lessonsExtracted,
      metadataExtracted,
    },
  };
}

/**
 * Infer concept metadata from concept structure
 */
function inferConceptMetadata(
  concept: import('../types/concept').Concept,
  conceptGraph: StoredConceptGraph
): {
  difficulty?: number;
  timeEstimate?: number;
  domain?: string;
  tags?: string[];
  resourceLinks?: string[];
} | null {
  const metadata: {
    difficulty?: number;
    timeEstimate?: number;
    domain?: string;
    tags?: string[];
    resourceLinks?: string[];
  } = {};

  // Infer difficulty
  if (concept.difficulty) {
    const difficultyMap: Record<string, number> = {
      beginner: 1,
      intermediate: 3,
      advanced: 5,
    };
    metadata.difficulty = difficultyMap[concept.difficulty] || 2;
  } else {
    // Infer from description keywords
    const description = (concept.description || '').toLowerCase();
    if (description.includes('advanced') || description.includes('complex') || description.includes('expert')) {
      metadata.difficulty = 4;
    } else if (description.includes('intermediate') || description.includes('moderate')) {
      metadata.difficulty = 3;
    } else if (description.includes('basic') || description.includes('simple') || description.includes('introduction')) {
      metadata.difficulty = 1;
    } else {
      // Infer from prerequisites count
      const prereqCount = concept.prerequisites?.length || 0;
      if (prereqCount >= 3) metadata.difficulty = 4;
      else if (prereqCount >= 2) metadata.difficulty = 3;
      else if (prereqCount >= 1) metadata.difficulty = 2;
      else metadata.difficulty = 2;
    }
  }

  // Estimate learning time
  let time = concept.lesson ? 2.0 : 1.0;
  if (concept.lesson) {
    const wordCount = concept.lesson.split(/\s+/).length;
    time = Math.max(time, wordCount / 2000);
  }
  time += (concept.children?.length || 0) * 0.5;
  metadata.timeEstimate = Math.round(time * 10) / 10;

  // Extract domain
  const domain = conceptGraph.focus || extractDomainFromSeed(conceptGraph) || 'general';
  metadata.domain = domain;

  // Generate tags
  metadata.tags = generateTags(concept, domain);

  return metadata;
}

/**
 * Extract domain from seed concept description
 */
function extractDomainFromSeed(conceptGraph: StoredConceptGraph): string | null {
  const seedConcept = Object.values(conceptGraph.concepts).find(
    c => c.id === conceptGraph.seedConceptId || c.isSeed
  );
  if (!seedConcept?.description) {
    return null;
  }

  const description = seedConcept.description.toLowerCase();
  const domainKeywords: Record<string, string[]> = {
    programming: ['programming', 'code', 'developer', 'software', 'application'],
    machine_learning: ['machine learning', 'ml', 'ai', 'artificial intelligence', 'neural network'],
    web_development: ['web', 'frontend', 'backend', 'html', 'css', 'javascript'],
    data_science: ['data science', 'data analysis', 'analytics', 'dataset'],
    language: ['language', 'speak', 'conversation', 'grammar', 'vocabulary'],
  };

  for (const [domain, keywords] of Object.entries(domainKeywords)) {
    if (keywords.some(keyword => description.includes(keyword))) {
      return domain;
    }
  }

  return null;
}

/**
 * Generate tags from concept name and description
 */
function generateTags(concept: import('../types/concept').Concept, domain: string): string[] {
  const tags: string[] = [];
  const stopWords = new Set(['the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by']);

  // Add domain as tag
  if (domain && domain !== 'general') {
    tags.push(domain);
  }

  // Extract keywords from concept name
  const nameWords = concept.name.toLowerCase().split(/\s+/);
  for (const word of nameWords) {
    const cleaned = word.replace(/[^a-z0-9]/g, '');
    if (cleaned.length > 2 && !stopWords.has(cleaned)) {
      tags.push(cleaned);
    }
  }

  // Extract keywords from description (first 100 words)
  if (concept.description) {
    const descWords = concept.description.toLowerCase().split(/\s+/).slice(0, 100);
    for (const word of descWords) {
      const cleaned = word.replace(/[^a-z0-9]/g, '');
      if (cleaned.length > 4 && !stopWords.has(cleaned) && !tags.includes(cleaned)) {
        tags.push(cleaned);
      }
    }
  }

  // Limit to 10 most relevant tags
  return tags.slice(0, 10);
}

/**
 * Generate graph-level metadata
 */
function generateGraphLevelMetadata(
  nodes: Record<string, GraphNode>,
  relationships: NodeBasedRelationship[]
): {
  totalConcepts?: number;
  totalRelationships?: number;
  averageDifficulty?: number;
  estimatedTotalTime?: number;
  domains?: string[];
  lastEmbeddingUpdate?: number;
} {
  const conceptNodes = Object.values(nodes).filter(n => n.type === 'Concept');
  const metadataNodes = Object.values(nodes).filter(n => n.type === 'ConceptMetadata');
  
  const totalConcepts = conceptNodes.length;
  const totalRelationships = relationships.length;

  // Calculate average difficulty
  const difficulties = metadataNodes
    .map(n => n.properties.difficulty)
    .filter((d): d is number => typeof d === 'number');
  const averageDifficulty = difficulties.length > 0
    ? difficulties.reduce((sum, d) => sum + d, 0) / difficulties.length
    : undefined;

  // Calculate estimated total time
  const timeEstimates = metadataNodes
    .map(n => n.properties.timeEstimate)
    .filter((t): t is number => typeof t === 'number');
  const estimatedTotalTime = timeEstimates.length > 0
    ? timeEstimates.reduce((sum, t) => sum + t, 0)
    : undefined;

  // Extract unique domains
  const domains = Array.from(
    new Set(
      metadataNodes
        .map(n => n.properties.domain)
        .filter((d): d is string => typeof d === 'string' && d !== 'general')
    )
  );

  return {
    totalConcepts,
    totalRelationships,
    averageDifficulty: averageDifficulty ? Math.round(averageDifficulty * 10) / 10 : undefined,
    estimatedTotalTime: estimatedTotalTime ? Math.round(estimatedTotalTime * 10) / 10 : undefined,
    domains: domains.length > 0 ? domains : undefined,
  };
}

/**
 * Remove undefined values from an object (Firestore doesn't support undefined)
 */
function removeUndefinedValues(obj: any): any {
  if (obj === null || obj === undefined) {
    return null;
  }
  
  if (Array.isArray(obj)) {
    return obj.map(removeUndefinedValues).filter(item => item !== undefined);
  }
  
  if (typeof obj === 'object') {
    const cleaned: any = {};
    for (const [key, value] of Object.entries(obj)) {
      if (value !== undefined) {
        cleaned[key] = removeUndefinedValues(value);
      }
    }
    return cleaned;
  }
  
  return obj;
}

/**
 * Save NodeBasedKnowledgeGraph to Firestore using transactions
 * Stores the graph in users/{uid}/knowledgeGraphs/{graphId}
 * 
 * @param uid - User ID
 * @param nodeBasedGraph - Graph to save
 * @param expectedVersion - Optional version number for optimistic locking. If provided and the graph version has changed, merges changes instead of overwriting.
 * @returns Saved graph (may be merged with concurrent changes)
 */
export async function saveNodeBasedKnowledgeGraph(
  uid: string,
  nodeBasedGraph: NodeBasedKnowledgeGraph,
  expectedVersion?: number
): Promise<NodeBasedKnowledgeGraph> {
  try {
    const db = getFirestore();
    const kgRef = db
      .collection('users')
      .doc(uid)
      .collection('knowledgeGraphs')
      .doc(nodeBasedGraph.id);

    // Import merge service dynamically to avoid circular dependencies
    const { mergeGraphMutations } = await import('./graphMergeService');

    return await db.runTransaction(async (transaction) => {
      const doc = await transaction.get(kgRef);

      let graphToSave: NodeBasedKnowledgeGraph;

      if (!doc.exists) {
        // Document doesn't exist - this is a first save
        if (expectedVersion !== undefined) {
          // If expectedVersion is provided, we expected the document to exist
          throw new Error(`Graph ${nodeBasedGraph.id} not found (expected version ${expectedVersion})`);
        }
        
        // First save - create new document with version 1
        graphToSave = {
          ...nodeBasedGraph,
          version: 1,
          updatedAt: Date.now(),
        };
      } else {
        // Document exists - proceed with version checking and merging
        const currentGraph = doc.data() as NodeBasedKnowledgeGraph;

        // Check if graph was modified by another operation
        const currentVersion = currentGraph.version || 0;
        const incomingVersion = expectedVersion !== undefined ? expectedVersion : (nodeBasedGraph.version || 0);

        if (expectedVersion !== undefined && currentVersion > incomingVersion) {
          // Graph was modified - merge instead of overwrite
          console.log(
            `[saveNodeBasedKnowledgeGraph] Graph ${nodeBasedGraph.id} was modified (current: ${currentVersion}, expected: ${incomingVersion}). Merging changes.`
          );

          graphToSave = mergeGraphMutations(currentGraph, nodeBasedGraph);
        } else {
          // No conflict - use incoming graph
          graphToSave = {
            ...nodeBasedGraph,
            version: currentVersion + 1,
            updatedAt: Date.now(),
          };
        }
      }

      // Prepare data for Firestore (ensure all fields are serializable)
      const kgData = removeUndefinedValues(graphToSave);

      console.log(
        `[saveNodeBasedKnowledgeGraph] Saving NodeBasedKnowledgeGraph ${nodeBasedGraph.id} for user ${uid} (version: ${kgData.version})`
      );
      console.log(
        `[saveNodeBasedKnowledgeGraph] Nodes count: ${Object.keys(kgData.nodes || {}).length}`
      );
      console.log(
        `[saveNodeBasedKnowledgeGraph] Relationships count: ${kgData.relationships?.length || 0}`
      );

      transaction.set(kgRef, kgData, { merge: false });

      return graphToSave;
    });
  } catch (error: any) {
    console.error(
      `[saveNodeBasedKnowledgeGraph] Error saving NodeBasedKnowledgeGraph ${nodeBasedGraph.id}:`,
      error
    );
    console.error(`[saveNodeBasedKnowledgeGraph] Error stack:`, error.stack);

    // Re-throw Firestore transaction errors as-is (they include retry info)
    if (error.code === 'failed-precondition' || error.code === 'aborted') {
      throw new Error(
        `Transaction failed for graph ${nodeBasedGraph.id}. This may indicate a concurrent modification. Please retry. Original error: ${error.message}`
      );
    }

    throw new Error(`Failed to save NodeBasedKnowledgeGraph: ${error.message}`);
  }
}

/**
 * Get NodeBasedKnowledgeGraph from Firestore
 */
export async function getNodeBasedKnowledgeGraph(
  uid: string,
  graphId: string
): Promise<NodeBasedKnowledgeGraph | null> {
  const db = getFirestore();
  const kgRef = db
    .collection('users')
    .doc(uid)
    .collection('knowledgeGraphs')
    .doc(graphId);

  const doc = await kgRef.get();

  if (!doc.exists) {
    return null;
  }

  return doc.data() as NodeBasedKnowledgeGraph;
}

/**
 * Convert LearningGoal to nodes and relationships
 * This is a helper function that can be called separately when learning goals are loaded
 * 
 * @param graphId - The graph ID (used for generating node IDs)
 * @param learningGoal - The learning goal to convert
 * @param nodeBasedGraph - The current node-based graph (for context)
 * @param seedConceptId - Optional seed concept ID for creating proper relationship
 */
export function convertLearningGoalToNodes(
  graphId: string,
  learningGoal: LearningGoal,
  nodeBasedGraph: NodeBasedKnowledgeGraph,
  seedConceptId?: string
): {
  nodes: GraphNode[];
  relationships: NodeBasedRelationship[];
} {
  const nodes: GraphNode[] = [];
  const relationships: NodeBasedRelationship[] = [];

  // Create LearningGoal node
  // Use a numeric index if learningGoal.id is numeric, otherwise use 0
  const goalIndex = typeof learningGoal.id === 'number' ? learningGoal.id : 0;
  const goalNodeId = generateNodeId('LearningGoal', { graphId, index: goalIndex });
  const goalNode = createGraphNode(
    goalNodeId,
    'LearningGoal',
    {
      id: goalNodeId,
      name: learningGoal.title,  // Map title to name property
      description: learningGoal.description,
      type: learningGoal.type,
      target: learningGoal.target,
      estimatedTime: learningGoal.estimatedTime,
      assessedLevel: learningGoal.assessedLevel,
      placementTestId: learningGoal.placementTestId,
      customMetadata: learningGoal.customMetadata,
      createdAt: learningGoal.createdAt,
      updatedAt: learningGoal.updatedAt,
    },
    learningGoal.createdAt,
    learningGoal.updatedAt
  );
  nodes.push(goalNode);

  // Create relationship: SeedConcept → belongsToGoal → LearningGoal
  // (Matches graphA structure where seed concept links to goal)
  if (seedConceptId) {
    relationships.push(
      createRelationship(seedConceptId, goalNodeId, 'belongsToGoal', 'forward', 1.0, {
        extractedFrom: 'learning_goal',
        confidence: 1.0,
      })
    );
  }

  // Convert milestones to Milestone nodes
  if (learningGoal.milestones && learningGoal.milestones.length > 0) {
    learningGoal.milestones.forEach((milestone, index) => {
      // Use numeric index - convert string IDs to numeric if needed
      const milestoneIndex = typeof milestone.id === 'number' ? milestone.id : index;
      const milestoneNodeId = generateNodeId('Milestone', {
        graphId,
        index: milestoneIndex,
      });
      const milestoneNode = createGraphNode(
        milestoneNodeId,
        'Milestone',
        {
          id: milestoneNodeId,
          name: milestone.title,  // Map title to name property
          description: milestone.description,
          targetDate: milestone.targetDate,
          completed: milestone.completed,
          completedAt: milestone.completedAt,
        },
        learningGoal.createdAt,
        learningGoal.updatedAt
      );
      nodes.push(milestoneNode);

      // Create relationship: LearningGoal → hasMilestone → Milestone
      relationships.push(
        createRelationship(goalNodeId, milestoneNodeId, 'hasMilestone', 'forward', 1.0, {
          extractedFrom: 'learning_goal',
          confidence: 1.0,
        })
      );

      // Create relationship: Milestone → belongsToGoal → LearningGoal
      relationships.push(
        createRelationship(milestoneNodeId, goalNodeId, 'belongsToGoal', 'backward', 1.0, {
          extractedFrom: 'learning_goal',
          confidence: 1.0,
        })
      );

      // Create sequence relationships between milestones
      if (index > 0) {
        const prevMilestone = learningGoal.milestones![index - 1];
        const prevMilestoneIndex = typeof prevMilestone.id === 'number' ? prevMilestone.id : index - 1;
        const prevMilestoneId = generateNodeId('Milestone', {
          graphId,
          index: prevMilestoneIndex,
        });
        relationships.push(
          createRelationship(prevMilestoneId, milestoneNodeId, 'precedesMilestone', 'forward', 1.0, {
            extractedFrom: 'learning_goal',
            confidence: 1.0,
          })
        );
        relationships.push(
          createRelationship(milestoneNodeId, prevMilestoneId, 'followsMilestone', 'backward', 1.0, {
            extractedFrom: 'learning_goal',
            confidence: 1.0,
          })
        );
      }
    });
  }

  // Create relationships: LearningGoal → hasShortTermGoal → Layers
  if (learningGoal.shortTermGoals && learningGoal.shortTermGoals.length > 0) {
    for (const layerGoal of learningGoal.shortTermGoals) {
      // Try to find the layer node by goal text or layer number
      const layerNodes = Object.values(nodeBasedGraph.nodes).filter(
        (node) => node.type === 'Layer' && node.properties.goal === layerGoal
      );
      for (const layerNode of layerNodes) {
        relationships.push(
          createRelationship(goalNodeId, layerNode.id, 'hasShortTermGoal', 'forward', 1.0, {
            extractedFrom: 'learning_goal',
            confidence: 1.0,
          })
        );
      }
    }
  }

  return { nodes, relationships };
}
