import { Concept, OperationResult, ConceptGraph } from '../types/concept';
import { explainSystemPrompt } from '../prompts';
import { callLLM } from '../services/llm';
import { validateConcept } from '../utils/validation';
import { processPrerequisitesFromLesson } from '../utils/prerequisites';
import type { LearningGoal } from '../types/goal';
import { getGoalTypeGuidance } from '../utils/goalGuidance';

/**
 * Generates a detailed Markdown explanation (lesson) for a concept.
 * @param concept - Concept to explain
 * @param seedConcept - Optional seed/root concept for additional context anchoring
 * @returns Array with a single concept representing the lesson content
 */
interface ExplainOptions {
  simple?: boolean;
  minimal?: boolean; // If true, removes learning science tags AND practice questions
  uid?: string;
  graph?: ConceptGraph;
  stream?: boolean;
  learningGoal?: LearningGoal; // Learning goal for goal-aware explanations
  // REMOVED: difficulty (comes from LearningGoal or graph metadata)
  // REMOVED: focus (comes from LearningGoal or graph metadata)
}

export async function explain(
  concept: Concept,
  seedConcept?: Concept,
  options: ExplainOptions = {}
): Promise<OperationResult> {
  if (!validateConcept(concept)) {
    throw new Error('Invalid concept input for explain operation');
  }

  const { simple = false, minimal = false, stream = false, learningGoal, graph } = options;

  // Skip prerequisites for auto-generated concepts
  const skipPrerequisites = concept.isAutoGenerated === true;

  // Extract difficulty and focus from LearningGoal (not from options)
  const difficulty = learningGoal?.assessedLevel 
    ?? learningGoal?.customMetadata?.difficulty 
    ?? (seedConcept?.difficulty)
    ?? 'intermediate'; // Default fallback
  
  const focus = learningGoal?.customMetadata?.focus 
    ?? learningGoal?.description 
    ?? (seedConcept?.focus);

  const difficultyText = difficulty 
    ? difficulty === 'beginner' 
      ? 'beginner-level' 
      : difficulty === 'intermediate' 
        ? 'intermediate-level' 
        : 'advanced-level'
    : '';

  // Extract the goal from the top-level concept this concept belongs to
  let currentGoal: string | undefined;

  if (graph && seedConcept) {
    // Find the top-level concept (level concept) this concept belongs to
    // A level concept is a top-level concept (has seedConcept as its only parent)
    let topLevelConcept: Concept | undefined;
    
    // Check if this concept itself is a level concept
    const isLevelConcept = concept.parents.length === 1 && 
      concept.parents[0] === seedConcept.name &&
      concept.name !== seedConcept.name;
    
    if (isLevelConcept) {
      topLevelConcept = concept;
    } else {
      // Find the level concept in the parent chain
      // Check direct parents first
      for (const parentName of concept.parents) {
        if (parentName === seedConcept.name) continue;
        
        const parentConcept = graph.concepts?.get(parentName);
        if (parentConcept && 
            parentConcept.parents.length === 1 && 
            parentConcept.parents[0] === seedConcept.name) {
          topLevelConcept = parentConcept;
          break;
        }
      }
      
      // If not found in direct parents, traverse up the parent chain
      if (!topLevelConcept) {
        const visited = new Set<string>();
        const findLevelConcept = (conceptName: string): Concept | undefined => {
          if (visited.has(conceptName)) return undefined;
          visited.add(conceptName);
          
          const currentConcept = graph.concepts?.get(conceptName);
          if (!currentConcept) return undefined;
          
          // Check if this is a level concept
          if (currentConcept.parents.length === 1 && 
              currentConcept.parents[0] === seedConcept.name &&
              currentConcept.name !== seedConcept.name) {
            return currentConcept;
          }
          
          // Recursively check parents
          for (const parentName of currentConcept.parents) {
            if (parentName === seedConcept.name) continue;
            const found = findLevelConcept(parentName);
            if (found) return found;
          }
          
          return undefined;
        };
        
        topLevelConcept = findLevelConcept(concept.name);
      }
    }

    // Extract the goal from the top-level concept
    if (topLevelConcept?.goal) {
      currentGoal = topLevelConcept.goal;
    }
  }

  // Goal type-specific guidance
  const goalTypeGuidance = getGoalTypeGuidance(learningGoal);

  const seedInfo = seedConcept
    ? `The learner is studying the broader topic "${seedConcept.name}".${difficulty ? ` The learner is at a ${difficultyText} level.` : ''}${focus ? ` The learning focus is: "${focus}".` : ''}${currentGoal ? ` The current learning goal for this layer is: "${currentGoal}".` : ''} `
    : currentGoal
    ? `The current learning goal for this layer is: "${currentGoal}".${difficulty ? ` The learner is at a ${difficultyText} level.` : ''}${focus ? ` The learning focus is: "${focus}".` : ''} `
    : '';

  const conceptContext = `Concept Name: ${concept.name}
Current Summary: ${concept.description}
Known Parents: ${concept.parents.length > 0 ? concept.parents.join(', ') : 'none'}
Known Children: ${concept.children.length > 0 ? concept.children.join(', ') : 'none'}
Layer: ${concept.layer !== undefined ? concept.layer : 'unspecified'}${difficulty ? `\nLearner Level: ${difficultyText}` : ''}${focus ? `\nLearning Focus: ${focus}` : ''}${currentGoal ? `\nCurrent Goal: ${currentGoal}` : ''}
${goalTypeGuidance ? `\n${goalTypeGuidance}` : ''}
`;

  // Build learning science tags instructions
  // Filter parent concepts to exclude:
  // 1. Seed concept itself
  // 2. Level concepts (those whose only parent is the seed concept)
  const parentConcepts = concept.parents.filter(p => {
    // Exclude seed concept
    if (p === seedConcept?.name) return false;
    
    // Exclude level concepts by checking if this parent concept
    // has only the seed concept as its parent
    if (options.graph?.concepts) {
      const parentConceptData = options.graph.concepts.get(p);
      if (parentConceptData) {
        // Check if this parent is a level concept
        // (has exactly 1 parent, which is the seed concept)
        const isLevelConcept = 
          parentConceptData.parents &&
          parentConceptData.parents.length === 1 &&
          parentConceptData.parents[0] === seedConcept?.name;
        
        if (isLevelConcept) return false;
      }
    }
    
    return true; // Keep all other parents
  });
  
  const learningScienceTags = `
LEARNING SCIENCE TAGS (REQUIRED):

1. **Activation Tag** - Start the lesson with:
   <activate>
   A thought-provoking question about prior knowledge (1-2 sentences, e.g., "What do you already know about...?")
   </activate>

2. **Connection Tag** - Immediately after activation${parentConcepts.length > 0 ? `, reference parent concepts: ${parentConcepts.join(', ')}` : ''}:
   <connect>
   This builds on:
   ${parentConcepts.length > 0 ? parentConcepts.map(p => `- **${p}**: [one-sentence reminder of what this concept means]`).join('\n   ') : '- No prior concepts (this is foundational)'}
   </connect>
   ${parentConcepts.length === 0 ? '(You may skip <connect> tag if no parent concepts)' : ''}

3. **Reflection Tags** - Insert 1-2 reflection prompts throughout the lesson:
   <reflect>
   One sentence question encouraging elaboration or real-world connections
   </reflect>
   - Place after key concepts are introduced
   - Keep questions short and specific

4. **Bloom's Taxonomy Tags** - Wrap ALL practice questions with cognitive level:
   <bloom level="[remember|understand|apply|analyze|evaluate|create]">
   <question>...</question>
   <answer>...</answer>
   </bloom>
   - Use at least 2-3 different Bloom levels
   - Progress from lower to higher cognitive levels
   - Choose the level that matches the question's cognitive demand

Tag Placement Rules:
- <activate> MUST be the very first element in the lesson
- <connect> immediately after <activate>
- <reflect> tags inline within lesson content (1-2 total)
- <bloom> wraps existing <question>/<answer> pairs
- Do NOT nest tags incorrectly or place them in wrong order
`;

  // Determine if we should include learning science tags and practice questions
  const includeLearningScienceTags = !minimal && !simple;
  const includePracticeQuestions = !minimal;

  const userPrompt = simple
    ? `${seedInfo}Create a concise lesson for the concept below.

${conceptContext}
${includeLearningScienceTags ? learningScienceTags : ''}

Guidelines:
- Output only Markdown text (no JSON, no metadata).
- Keep it short and focused.${focus ? ` Maintain focus on "${focus}" throughout the lesson.` : ''}${currentGoal ? ` **CRITICAL: This lesson must align with the current goal: "${currentGoal}". Stay focused on what's needed for this goal only.` : ''}
- Include a single level-1 heading for the lesson title (you may reuse "${concept.name}" with a qualifier).
- Keep this lesson to the context of "${seedConcept?.name}".${focus ? ` Ensure all content aligns with the learning focus: "${focus}".` : ''}${currentGoal ? ` Ensure all content is relevant to and supports the current goal: "${currentGoal}".` : ''}
${!skipPrerequisites ? `- START with prerequisites: Begin the lesson by listing any prerequisite concepts or foundational knowledge needed, wrapped in <prq>...</prq> block listing separated by commas if multiple. Use simple, single-concept names only. Avoid long descriptive names, parentheses, or special characters. If there are no prerequisites, you may omit this section.` : ''}
- Provide a very brief, simple explanatory paragraph (1-2 sentences maximum; no analogies; be direct and concise).${focus ? ` Relate the explanation to the learning focus: "${focus}".` : ''}${currentGoal ? ` Connect the explanation to how it helps achieve the current goal: "${currentGoal}".` : ''}
- Include exactly one illustrative example (code or math if relevant) under a level-2 heading.${focus ? ` The example should demonstrate concepts relevant to "${focus}".` : ''}${currentGoal ? ` The example should be relevant to the current goal: "${currentGoal}".` : ''}
${includePracticeQuestions ? `- Add a quick practice section with 2-3 questions, each wrapped in <bloom> tags with appropriate cognitive level.
${focus ? `- All practice questions must be relevant to the learning focus: "${focus}".` : ''}${currentGoal ? ` All practice questions must be relevant to the current goal: "${currentGoal}".` : ''}
- Do NOT generate matching questions. Only use multiple choice questions.
- Do not wrap the <question>/<answer> pairs inside lists or extra Markdown containers. Present each pair directly, separated by blank lines.` : ''}
${!skipPrerequisites ? `- Do not wrap the <prq>...</prq> tags inside lists or extra Markdown containers. Present it directly.` : ''}
${minimal ? `- Keep this as a general overview only. Do NOT include:
  * Key takeaways or summary sections
  * Practice questions or exercises
  * Additional sections beyond the core explanation` : `- Do not add additional sections or commentary beyond these requirements.
- Include any relevant references or further reading.`}
${difficulty ? `
- **Learner Level**: Tailor the content to ${difficultyText} learners.` : ''}`
    : `${seedInfo}Your task is to design a master-quality lesson for the concept detailed below.

${conceptContext}
${includeLearningScienceTags ? learningScienceTags : ''}

Output the lesson as pure Markdown text only (no JSON, no metadata keys, no commentary outside the Markdown).

Markdown requirements:
- Keep this lesson to the context of "${seedConcept?.name}".${focus ? ` Maintain focus on "${focus}" throughout all sections of the lesson.` : ''}${currentGoal ? ` **CRITICAL: This lesson must align with the current goal: "${currentGoal}". Stay focused on what's needed for this goal only.` : ''}
${!skipPrerequisites ? `- Start with prerequisites: Begin the lesson by listing any prerequisite concepts or foundational knowledge needed, wrapped in <prq>...</prq> block listing separated by commas if multiple. Use simple, single-concept names. Avoid long descriptive names, parentheses, or special characters. If there are no prerequisites, you may omit this section.` : ''}
- Provide a concise introductory section (2-3 sentences) outlining goals, context, and why the concept matters. Keep it brief and focused.${focus ? ` Emphasize how this concept relates to the learning focus: "${focus}".` : ''}${currentGoal ? ` Explain how this concept helps achieve the current goal: "${currentGoal}".` : ''}
- Organize the explanation into clear sections (level-2+ headings) that progressively deepen understanding.${focus ? ` Ensure all sections align with and support the learning focus: "${focus}".` : ''}${currentGoal ? ` Ensure all sections support progress toward the current goal: "${currentGoal}".` : ''}
- Include illustrative examples; when helpful, embed fenced code blocks with language identifiers or LaTeX formulas between $$ fences.${focus ? ` Examples should demonstrate concepts relevant to "${focus}".` : ''}${currentGoal ? ` Examples should be relevant to the current goal: "${currentGoal}".` : ''}
- Share real-world applications or case studies when appropriate.${focus ? ` Applications should relate to the learning focus: "${focus}".` : ''}${currentGoal ? ` Applications should demonstrate how this concept applies to the current goal: "${currentGoal}".` : ''}
${includeLearningScienceTags ? `- Insert 2-3 <reflect> tags at natural breakpoints throughout the lesson.` : ''}
${includePracticeQuestions ? `- Include a practice section with concrete exercises, reflection prompts, or small projects, each wrapped in <bloom> tags with appropriate cognitive level (use at least 3 different levels).
${focus ? `- All practice exercises must be relevant to and support the learning focus: "${focus}".` : ''}${currentGoal ? ` All practice exercises must be relevant to the current goal: "${currentGoal}".` : ''}
- Do NOT generate matching questions. Only use multiple choice questions.
- Do not wrap the <question>/<answer> pairs inside lists or extra Markdown containers. Present each pair directly, separated by blank lines.` : ''}
${!skipPrerequisites ? `- Do not wrap the <prq>...</prq> tags inside lists or extra Markdown containers. Present it directly.` : ''}
${minimal ? `- Keep this as a general overview only. Do NOT include:
  * Key takeaways or summary sections
  * Practice questions or exercises
  * Additional sections beyond the core explanation` : `- Conclude with key takeaways or a concise summary.${focus ? ` Relate the takeaways to the learning focus: "${focus}".` : ''}
- Include any relevant references or further reading.`}

Style notes:
- Be precise, factual, and supportive.
- Avoid hallucinations; if information is uncertain or assumptions are needed, state them explicitly.
- Ensure the Markdown renders cleanly with appropriate spacing.
${difficulty ? `
- **Learner Level**: Tailor all content to ${difficultyText} learners.` : ''}

Again, return ONLY the Markdown lesson text.`;

  // Build full prompt (system + user) for return
  const fullPrompt = `${explainSystemPrompt}\n\n${userPrompt}`;

  const response = await callLLM({
    systemPrompt: explainSystemPrompt,
    userPrompt,
    provider: 'deepseek',
    model: 'deepseek-chat',
    uid: options.uid,
    stream: stream
  });

  // If streaming, return the stream with prompt
  if (response.stream && response.raw) {
    return {
      stream: response.raw,
      model: response.model,
      prompt: fullPrompt,
    } as any;
  }

  // Trim only removes leading/trailing whitespace, preserving all internal newlines
  const lessonMarkdown = response.content.trim();

  if (!lessonMarkdown) {
    throw new Error('Explain operation returned empty content');
  }

  // Process prerequisites using centralized function
  const prerequisites = processPrerequisitesFromLesson(lessonMarkdown, concept, options.graph);

  const lessonConcept: Concept = {
    ...concept,
    lesson: lessonMarkdown,
    prerequisites,
  };

  const result = [lessonConcept] as OperationResult & { prompt?: string };
  result.prompt = fullPrompt;
  return result;
}

