/**
 * Node-Based Graph Extractor
 * 
 * Utility functions to extract data from NodeBasedKnowledgeGraph
 * for use with operations that expect the old format.
 */

import type {
  NodeBasedKnowledgeGraph,
} from '../types/nodeBasedKnowledgeGraph';
import type {
  EnhancedConcept,
  Relationship,
} from '../types/knowledgeGraph';
import {
  getNodesByType,
  getConnectedNodes,
  getLessonForConcept,
  getMetadataForConcept,
  getFlashCardsForConcept,
} from './nodeBasedGraphQueries';

/**
 * Extract concepts and relationships from NodeBasedKnowledgeGraph
 * in the format expected by enrichment operations
 */
export function extractGraphForOperations(
  nodeBasedGraph: NodeBasedKnowledgeGraph
): {
  concepts: Record<string, EnhancedConcept>;
  relationships?: Record<string, Relationship[]>;
} {
  const concepts: Record<string, EnhancedConcept> = {};
  const relationships: Record<string, Relationship[]> = {};

  // Get all concept nodes
  const conceptNodes = getNodesByType(nodeBasedGraph, 'Concept');

  // Convert concept nodes to EnhancedConcept
  for (const conceptNode of conceptNodes) {
    const conceptId = conceptNode.id;
    const props = conceptNode.properties;

    // Get lesson if exists
    const lessonNode = getLessonForConcept(nodeBasedGraph, conceptId);
    const lesson = lessonNode?.properties.content;

    // Get metadata if exists
    const metadataNode = getMetadataForConcept(nodeBasedGraph, conceptId);
    const metadata = metadataNode
      ? {
          difficulty: metadataNode.properties.difficulty,
          timeEstimate: metadataNode.properties.timeEstimate,
          domain: metadataNode.properties.domain,
          tags: metadataNode.properties.tags,
          resourceLinks: metadataNode.properties.resourceLinks,
        }
      : undefined;

    // Get flash cards
    const flashCardNodes = getFlashCardsForConcept(nodeBasedGraph, conceptId);
    const flash = flashCardNodes.map((card) => ({
      front: card.properties.front,
      back: card.properties.back,
    }));

    // Get parent/child relationships
    const parentNodes = getConnectedNodes(nodeBasedGraph, conceptId, 'hasParent', 'outgoing');
    const childNodes = getConnectedNodes(nodeBasedGraph, conceptId, 'hasChild', 'outgoing');
    const prerequisiteNodes = getConnectedNodes(
      nodeBasedGraph,
      conceptId,
      'hasPrerequisite',
      'outgoing'
    );

    // Get layer relationship
    const layerNodes = getConnectedNodes(nodeBasedGraph, conceptId, 'belongsToLayer', 'outgoing');
    const layer = layerNodes.length > 0 ? layerNodes[0].properties.layerNumber : undefined;

    // Build concept
    const concept: EnhancedConcept = {
      id: props.id || conceptId,
      name: props.name,
      description: props.description,
      parents: parentNodes.map((n) => n.id),
      children: childNodes.map((n) => n.id),
      prerequisites: prerequisiteNodes.map((n) => n.id),
      lesson,
      flash: flash.length > 0 ? flash : undefined,
      sequence: props.sequence,
      focus: props.focus,
      isSeed: props.isSeed || false,
      isAutoGenerated: props.isAutoGenerated || false,
      isPrerequisite: props.isPrerequisite || false,
      layer,
      metadata,
      goal: props.goal,
    };

    concepts[conceptId] = concept;

    // Build relationships array for this concept
    const conceptRelationships: Relationship[] = [];
    
    // Parent relationships
    for (const parentNode of parentNodes) {
      conceptRelationships.push({
        target: parentNode.id,
        type: 'hierarchical',
        strength: 1.0,
        direction: 'backward',
        metadata: {
          extractedFrom: 'concept_structure',
          confidence: 1.0,
        },
      });
    }

    // Child relationships
    for (const childNode of childNodes) {
      conceptRelationships.push({
        target: childNode.id,
        type: 'hierarchical',
        strength: 1.0,
        direction: 'forward',
        metadata: {
          extractedFrom: 'concept_structure',
          confidence: 1.0,
        },
      });
    }

    // Prerequisite relationships
    for (const prereqNode of prerequisiteNodes) {
      conceptRelationships.push({
        target: prereqNode.id,
        type: 'prerequisite',
        strength: 0.9,
        direction: 'backward',
        metadata: {
          extractedFrom: 'prerequisites',
          confidence: 0.9,
        },
      });
    }

    if (conceptRelationships.length > 0) {
      relationships[conceptId] = conceptRelationships;
    }
  }

  return {
    concepts,
    relationships: Object.keys(relationships).length > 0 ? relationships : undefined,
  };
}

/**
 * Extract layers from NodeBasedKnowledgeGraph
 */
export function extractLayersFromNodeBasedGraph(
  nodeBasedGraph: NodeBasedKnowledgeGraph
): Array<{ layerNumber: number; concepts: EnhancedConcept[] }> {
  const { concepts } = extractGraphForOperations(nodeBasedGraph);
  const layers: Array<{ layerNumber: number; concepts: EnhancedConcept[] }> = [];

  // Get all layer nodes
  const layerNodes = getNodesByType(nodeBasedGraph, 'Layer');

  for (const layerNode of layerNodes) {
    const layerNumber = layerNode.properties.layerNumber;
    
    // Get concepts in this layer
    const conceptNodes = getConnectedNodes(nodeBasedGraph, layerNode.id, 'containsConcept', 'outgoing')
      .filter(n => n.type === 'Concept');

    const layerConcepts = conceptNodes
      .map(n => concepts[n.id])
      .filter((c): c is EnhancedConcept => c !== undefined);

    layers.push({ layerNumber, concepts: layerConcepts });
  }

  return layers.sort((a, b) => a.layerNumber - b.layerNumber);
}

