import { Concept, ConceptGraph } from '../types/concept';

/**
 * Parses prerequisite concept names from lesson text containing <prq> tags
 * @param lesson - Lesson markdown text that may contain <prq>...</prq> tags
 * @returns Array of prerequisite concept names
 */
export function parsePrerequisitesFromLesson(lesson: string): string[] {
  if (!lesson) {
    return [];
  }

  const prerequisites: string[] = [];
  
  // Match <prq>...</prq> tags (case-insensitive, handles whitespace)
  const prqRegex = /<prq>([\s\S]*?)<\/prq>/gi;
  let match: RegExpExecArray | null;
  
  while ((match = prqRegex.exec(lesson)) !== null) {
    const content = match[1]?.trim();
    if (!content) {
      continue;
    }

    // Split by comma and clean up each prerequisite name
    const names = content
      .split(',')
      .map((name: string) => {
        // Extract the concept name part (before any parentheses with descriptions)
        // Example: "Basic understanding of programming concepts (variables, functions)" 
        // -> "Basic understanding of programming concepts"
        const trimmed = name.trim();
        const parenIndex = trimmed.indexOf('(');
        if (parenIndex > 0) {
          // Take only the part before the opening parenthesis
          return trimmed.substring(0, parenIndex).trim();
        }
        return trimmed;
      })
      .filter((name: string) => name.length > 0)
      .filter((name: string) => name.toLowerCase() !== 'none');

    prerequisites.push(...names);
  }

  // Remove duplicates and return
  return Array.from(new Set(prerequisites));
}

/**
 * Checks which prerequisites exist in the graph and which are missing
 * @param prerequisites - Array of prerequisite concept names to check
 * @param graph - Concept graph to search in
 * @returns Object with existing and missing prerequisite arrays
 */
export function checkPrerequisitesExist(
  prerequisites: string[],
  graph: ConceptGraph
): { existing: string[]; missing: string[] } {
  const existing: string[] = [];
  const missing: string[] = [];

  const conceptMap = graph.concepts;
  
  for (const prereqName of prerequisites) {
    // Skip "none"
    if (!prereqName || prereqName.trim().toLowerCase() === 'none') {
      continue;
    }
    
    // Check if concept exists in graph (case-insensitive search)
    const normalizedPrereq = prereqName.trim();
    let found = false;

    conceptMap.forEach((concept, conceptName) => {
      if (conceptName.toLowerCase() === normalizedPrereq.toLowerCase() ||
          concept.name.toLowerCase() === normalizedPrereq.toLowerCase()) {
        existing.push(prereqName);
        found = true;
      }
    });

    if (!found) {
      missing.push(prereqName);
    }
  }

  return { existing, missing };
}

/**
 * Assigns an appropriate layer for a prerequisite concept
 * @param concept - The concept that requires the prerequisite
 * @param prerequisiteName - Name of the prerequisite
 * @returns Suggested layer number for the prerequisite
 */
export function assignPrerequisiteLayer(concept: Concept, prerequisiteName: string): number {
  // If concept has a layer, place prerequisite one layer earlier
  if (concept.layer !== undefined && concept.layer > 0) {
    return concept.layer - 1;
  }
  // Otherwise, place at layer 0 (foundational)
  return 0;
}

/**
 * Centralized function to process prerequisites from a lesson
 * Parses prerequisites from lesson content and filters out existing ones
 * @param lessonContent - The lesson markdown content
 * @param concept - The concept being explained
 * @param graph - Optional concept graph to check for existing prerequisites
 * @returns Array of missing prerequisites, or undefined if none or concept is auto-generated
 */
export function processPrerequisitesFromLesson(
  lessonContent: string,
  concept: Concept,
  graph?: ConceptGraph
): string[] | undefined {
  // Skip prerequisites for auto-generated concepts
  if (concept.isAutoGenerated === true) {
    return undefined;
  }

  // Parse prerequisites from the lesson
  const allPrerequisites = parsePrerequisitesFromLesson(lessonContent);

  if (allPrerequisites.length === 0) {
    return undefined;
  }

  // Filter out prerequisites that already exist in the graph
  if (graph) {
    const missingPrerequisites = allPrerequisites.filter((prereqName: string) => {
      const normalizedPrereq = prereqName.trim().toLowerCase();
      let found = false;
      
      graph.concepts.forEach((existingConcept, conceptName) => {
        if (
          conceptName.toLowerCase() === normalizedPrereq ||
          existingConcept.name.toLowerCase() === normalizedPrereq
        ) {
          found = true;
        }
      });
      
      return !found;
    });

    return missingPrerequisites.length > 0 ? missingPrerequisites : undefined;
  }

  // If no graph provided, return all prerequisites
  return allPrerequisites.length > 0 ? allPrerequisites : undefined;
}

