import { Concept, ExtendedConcept, ConceptGraph } from '../types/concept';
import { generateConceptId } from './uuid';

/**
 * Validates that an object conforms to the Concept schema
 */
export function validateConcept(obj: any): obj is Concept {
  if (!obj || typeof obj !== 'object') {
    return false;
  }

  if (typeof obj.name !== 'string' || obj.name.length === 0) {
    return false;
  }

  if (typeof obj.description !== 'string') {
    return false;
  }

  if (!Array.isArray(obj.parents)) {
    return false;
  }

  if (!obj.parents.every((p: any) => typeof p === 'string')) {
    return false;
  }

  if (!Array.isArray(obj.children)) {
    return false;
  }

  if (!obj.children.every((c: any) => typeof c === 'string')) {
    return false;
  }

  if (obj.lesson !== undefined && typeof obj.lesson !== 'string') {
    return false;
  }

  if (obj.sequence !== undefined && typeof obj.sequence !== 'number') {
    return false;
  }

  if (obj.focus !== undefined && typeof obj.focus !== 'string') {
    return false;
  }

  if (obj.difficulty !== undefined && !['beginner', 'intermediate', 'advanced'].includes(obj.difficulty)) {
    return false;
  }

  if (obj.prerequisites !== undefined && !Array.isArray(obj.prerequisites)) {
    return false;
  }

  if (obj.prerequisites !== undefined && !obj.prerequisites.every((p: any) => typeof p === 'string')) {
    return false;
  }

  if (obj.isAutoGenerated !== undefined && typeof obj.isAutoGenerated !== 'boolean') {
    return false;
  }

  return true;
}

/**
 * Validates that an object conforms to the ExtendedConcept schema
 */
export function validateExtendedConcept(obj: any): obj is ExtendedConcept {
  if (!validateConcept(obj)) {
    return false;
  }

  const extended = obj as ExtendedConcept;

  // Optional fields validation
  if (extended.attention_score !== undefined) {
    if (typeof extended.attention_score !== 'number' || 
        extended.attention_score < 0 || 
        extended.attention_score > 1) {
      return false;
    }
  }

  if (extended.validation_score !== undefined) {
    if (typeof extended.validation_score !== 'number' || 
        extended.validation_score < 0 || 
        extended.validation_score > 1) {
      return false;
    }
  }

  if (extended.importance !== undefined) {
    if (!['low', 'medium', 'high'].includes(extended.importance)) {
      return false;
    }
  }

  return true;
}

/**
 * Validates an array of concepts
 */
export function validateConceptArray(concepts: any[]): concepts is Concept[] {
  return Array.isArray(concepts) && concepts.every(validateConcept);
}

/**
 * Ensures a concept has the minimal required structure
 * Fills in missing required fields with defaults
 * Generates an ID if one doesn't exist
 */
export function normalizeConcept(obj: any): Concept {
  return {
    id: obj.name || generateConceptId(), // Generate ID if not present
    name: obj.name || '',
    description: obj.description || '',
    goal: typeof obj.goal === 'string' ? obj.goal : undefined,
    parents: Array.isArray(obj.parents) ? obj.parents.filter((p: any) => typeof p === 'string') : [],
    children: Array.isArray(obj.children) ? obj.children.filter((c: any) => typeof c === 'string') : [],
    layer: typeof obj.layer === 'number' ? obj.layer : undefined,
    subLayer: typeof obj.subLayer === 'string' ? obj.subLayer : undefined,
    lesson: typeof obj.lesson === 'string' ? obj.lesson : undefined,
    sequence: typeof obj.sequence === 'number' ? obj.sequence : undefined,
    focus: typeof obj.focus === 'string' ? obj.focus : undefined,
    difficulty: ['beginner', 'intermediate', 'advanced'].includes(obj.difficulty) ? obj.difficulty : undefined,
    prerequisites: Array.isArray(obj.prerequisites) ? obj.prerequisites.filter((p: any) => typeof p === 'string') : undefined,
    isAutoGenerated: typeof obj.isAutoGenerated === 'boolean' ? obj.isAutoGenerated : undefined,
    isSeed: typeof obj.isSeed === 'boolean' ? obj.isSeed : undefined,
    flash: Array.isArray(obj.flash) ? obj.flash.filter((card: any) => 
      card && typeof card === 'object' && typeof card.front === 'string' && typeof card.back === 'string'
    ).map((card: any) => ({
      front: card.front.trim(),
      back: card.back.trim(),
    })) : undefined,
  };
}

/**
 * Checks if adding a concept as a child of another would create a circular dependency.
 * A circular dependency occurs when the target concept (or any of its descendants) is
 * already an ancestor of the dragged concept.
 * 
 * This is a central validation function that should be used whenever parent-child
 * relationships are modified to prevent cycles in the concept graph.
 * 
 * @param childConcept - The concept that would become a child
 * @param parentConcept - The concept that would become the parent
 * @param graph - The concept graph containing all concepts
 * @returns true if adding would create a cycle, false otherwise
 */
export function wouldCreateCircularDependency(
  childConcept: Concept,
  parentConcept: Concept,
  graph: ConceptGraph
): boolean {
  // If adding to itself, that's a cycle
  if (childConcept.name === parentConcept.name) {
    return true;
  }

  // Get all ancestors of the child concept (recursively)
  const getAncestors = (concept: Concept, visited: Set<string> = new Set()): Set<string> => {
    if (visited.has(concept.name)) {
      return visited; // Prevent infinite loops in case of existing cycles
    }
    visited.add(concept.name);

    // Add all parents and their ancestors
    concept.parents.forEach(parentName => {
      const parent = graph.concepts.get(parentName);
      if (parent) {
        getAncestors(parent, visited);
      }
    });

    return visited;
  };

  // Get all ancestors of the child concept
  const childAncestors = getAncestors(childConcept);

  // Check if parent concept is an ancestor of child concept
  if (childAncestors.has(parentConcept.name)) {
    return true;
  }

  // Get all descendants of the parent concept (recursively)
  const getDescendants = (concept: Concept, visited: Set<string> = new Set()): Set<string> => {
    if (visited.has(concept.name)) {
      return visited; // Prevent infinite loops
    }
    visited.add(concept.name);

    // Add all children and their descendants
    concept.children.forEach(childName => {
      const child = graph.concepts.get(childName);
      if (child) {
        getDescendants(child, visited);
      }
    });

    return visited;
  };

  // Get all descendants of the parent concept
  const parentDescendants = getDescendants(parentConcept);

  // Check if any descendant of parent is an ancestor of child
  for (const descendantName of parentDescendants) {
    if (childAncestors.has(descendantName)) {
      return true;
    }
  }

  return false;
}

/**
 * Validates that a concept's parent-child relationships don't create circular dependencies.
 * Checks all parents of the concept to ensure none of them would create a cycle.
 * 
 * @param concept - The concept to validate
 * @param graph - The concept graph containing all concepts
 * @returns true if valid (no cycles), false if cycles detected
 */
export function validateNoCircularDependencies(
  concept: Concept,
  graph: ConceptGraph
): boolean {
  // Check each parent relationship
  for (const parentName of concept.parents) {
    const parent = graph.concepts.get(parentName);
    if (parent && wouldCreateCircularDependency(concept, parent, graph)) {
      return false;
    }
  }
  return true;
}

