/**
 * Difficulty level for learning paths (stored at graph level)
 */
export type GraphDifficulty = 'beginner' | 'intermediate' | 'advanced';

/**
 * Minimal Concept Schema - Core structure for all KFlow operations
 * All prompt functions must accept and return this structure
 */
export interface Concept {
  id?: string;              // ID generated on server side in normalizeConcept
  name: string;
  description: string;
  goal?: string;            // Goal for level concepts (top-level concepts that represent layers)
  parents: string[];      // Array of parent concept names
  children: string[];     // Array of child concept names
  layer?: number;         // Optional layer number for progressive expansion (deprecated - will be removed after migration)
  subLayer?: string;      // Optional sub-layer identifier (e.g., "1.2a", "2.1b") for progressiveExpandSingle
  lesson?: string;        // Optional markdown lesson generated by explain operation
  sequence?: number;      // Sequence order for maintaining insertion order in maps
  focus?: string;         // Learning focus extracted from seed concept description
  difficulty?: GraphDifficulty; // Difficulty level (legacy - now stored at graph level)
  prerequisites?: string[]; // Array of prerequisite concept names
  isAutoGenerated?: boolean; // Flag for concepts auto-created from prerequisites
  isPrerequisite?: boolean; // Flag indicating if this concept is a prerequisite for another concept
  flash?: FlashCard[]; // Array of flash cards for the concept
  isSeed?: boolean;     // Whether this is the seed concept
  questions?: QuestionAnswer[]; // Array of questions and answers asked about this concept
  notes?: NoteItem[]; // Array of user notes for the lesson
}

/**
 * Note item structure
 */
export interface NoteItem {
  id: string; // Unique ID for the note (also used as highlightId)
  text: string; // The note content
  selectedText?: string; // Full selected text for display
  selectedTextChunks?: string[]; // Chunks of selected text for highlighting
  timestamp?: number; // Timestamp when the note was created
}

/**
 * Question and answer structure
 */
export interface QuestionAnswer {
  question: string; // The question asked
  answer: string; // The answer received
  selectedText?: string; // Full selected text for display
  selectedTextChunks?: string[]; // Chunks of selected text for highlighting
  highlightId?: string; // Shared ID for all chunks (if not using question/answer ID)
  timestamp?: number; // Timestamp when the question was asked
}

/**
 * Flash card structure
 */
export interface FlashCard {
  front: string; // Question or prompt (front of the card)
  back: string; // Answer or explanation (back of the card)
}

/**
 * Extended Concept with optional metadata
 * Operations may add fields like attention_score, validation_score, etc.
 */
export interface ExtendedConcept extends Concept {
  attention_score?: number;      // 0-1 for refocus operations
  validation_score?: number;     // 0-1 for validate_links operations
  importance?: 'low' | 'medium' | 'high';  // For refocus operations
}

/**
 * Operation Result - Standard return type for all prompt functions
 * Can be an array of concepts or an object with concepts and optional prompt
 */
export type OperationResult = Concept[] | (Concept[] & { prompt?: string });

/**
 * Graph Store - In-memory representation of the concept graph
 */
export interface ConceptGraph {
  concepts: Map<string, Concept>;  // Keyed by concept name
}

/**
 * Composable function type signature
 */
export type ComposableFunction = (input: Concept | Concept[]) => Promise<OperationResult>;

