/**
 * Types for Knowledge Graph (enhanced ConceptGraph with relationships and metadata)
 * Part of Phase 2: Concept Graph to Knowledge Graph Conversion
 */

import type { Concept, GraphDifficulty } from './concept';

/**
 * Relationship types between concepts
 */
export type RelationshipType = 
  | 'prerequisite'    // A must be learned before B
  | 'complementary'    // A and B are related/complementary
  | 'hierarchical'     // A is a sub-concept of B
  | 'sequential'       // A typically comes before B
  | 'related';         // General relationship

/**
 * Direction of relationship
 */
export type RelationshipDirection = 
  | 'forward'         // A -> B
  | 'backward'        // A <- B
  | 'bidirectional';  // A <-> B

/**
 * Relationship metadata
 */
export interface RelationshipMetadata {
  extractedFrom?: string;  // Source of relationship (e.g., 'concept_structure', 'llm', 'user')
  confidence?: number;      // Confidence score (0-1)
}

/**
 * Enhanced relationship between concepts
 */
export interface Relationship {
  target: string;                    // Target concept name
  type: RelationshipType;             // Type of relationship
  strength?: number;                  // Strength of relationship (0-1)
  direction?: RelationshipDirection;  // Direction of relationship
  metadata?: RelationshipMetadata;    // Additional metadata
}

/**
 * Concept metadata for ML operations
 */
export interface ConceptMetadata {
  difficulty?: number;           // Difficulty level (1-5, where 1=easiest, 5=hardest)
  timeEstimate?: number;         // Estimated time to learn in hours
  resourceLinks?: string[];       // Links to external resources
  tags?: string[];                // Tags for categorization
  domain?: string;                // Domain/category (e.g., 'programming', 'mathematics')
}

/**
 * Graph embeddings (stored in Python service, referenced here for type completeness)
 */
export interface Embeddings {
  node2vec?: number[];    // Node2Vec embedding vector (128-256 dimensions)
  generatedAt?: number;   // Timestamp when embeddings were generated
  model?: string;         // Embedding model used (e.g., 'node2vec', 'graphsage')
  dimensions?: number;    // Number of dimensions
}

/**
 * Enhanced concept with metadata and embeddings
 */
export interface EnhancedConcept extends Concept {
  metadata?: ConceptMetadata;              // Enhanced metadata
  embeddings?: Embeddings;                // Graph embeddings (generated by Python service)
  goalRelevance?: Record<string, number>;  // Relevance scores for different learning goals (0-1)
}

/**
 * Graph-level metadata
 */
export interface GraphMetadata {
  totalConcepts?: number;           // Total number of concepts in the graph
  totalRelationships?: number;      // Total number of relationships
  averageDifficulty?: number;      // Average difficulty across all concepts (1-5)
  estimatedTotalTime?: number;      // Estimated total time to complete all concepts (hours)
  domains?: string[];               // List of domains covered by the graph
  lastEmbeddingUpdate?: number;     // Timestamp when embeddings were last updated
}

/**
 * Knowledge Graph - Enhanced ConceptGraph with relationships and metadata
 */
export interface KnowledgeGraph {
  // Core fields (from ConceptGraph)
  id: string;
  seedConceptId: string;
  concepts: Record<string, EnhancedConcept>;
  layers?: Record<number, any>;  // LayerData structure (preserved from ConceptGraph)
  createdAt: number;
  updatedAt: number;
  model?: string;
  goalFocused?: boolean;
  difficulty?: GraphDifficulty;
  focus?: string;
  
  // Enhanced fields (NEW - Phase 2)
  relationships?: Record<string, Relationship[]>;  // Map of concept names to their relationships
  metadata?: GraphMetadata;                         // Graph-level metadata
}

/**
 * Options for converting ConceptGraph to KnowledgeGraph
 */
export interface ConvertToKnowledgeGraphOptions {
  inferRelationships?: boolean;     // Infer relationships from structure (default: true)
  enhanceMetadata?: boolean;        // Enhance concept metadata (default: true)
  generateGraphMetadata?: boolean;  // Generate graph-level metadata (default: true)
  learningGoal?: {                  // Optional learning goal to populate seedConcept.goal if missing
    title: string;
    description: string;
  };
}

/**
 * Result of conversion operation
 */
export interface ConversionResult {
  knowledgeGraph: KnowledgeGraph;
  stats: {
    conceptsConverted: number;
    relationshipsInferred: number;
    metadataEnhanced: number;
  };
}

